#
# A Simple Makefile
#

######

include \
$(PATSHOME)/share/atsmake2-pre.mk

######

SOURCES_SATS += \
  calculator.sats \

SOURCES_DATS += \
  calculator.dats \
  calculator_aexp.dats \
  calculator_token.dats \
  calculator_cstream.dats \
  calculator_tstream.dats \
  calculator_parsing.dats \
  calculator_print.dats \

######

MYTARGET=calc

######

include $(PATSHOME)/share/atsmake2-post.mk

######

###### end of [Makefile] ######
