<?php
/*
**
** The PHP code is generated by atscc2php
** The starting compilation time is: 2016-12-19:  0h:23m
**
*/
function
_ats2phppre_arrayref_patsfun_8__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_arrayref_patsfun_8($cenv[1], $arg0); }, $env0);
}


function
ats2phppre_arrayref_exists_cloref($arg0, $arg1, $arg2)
{
//
  $tmpret0 = NULL;
//
  __patsflab_arrayref_exists_cloref:
  $tmpret0 = ats2phppre_int_exists_cloref($arg1, $arg2);
  return $tmpret0;
} // end-of-function


function
ats2phppre_arrayref_forall_cloref($arg0, $arg1, $arg2)
{
//
  $tmpret1 = NULL;
//
  __patsflab_arrayref_forall_cloref:
  $tmpret1 = ats2phppre_int_forall_cloref($arg1, $arg2);
  return $tmpret1;
} // end-of-function


function
ats2phppre_arrayref_foreach_cloref($arg0, $arg1, $arg2)
{
//
//
  __patsflab_arrayref_foreach_cloref:
  ats2phppre_int_foreach_cloref($arg1, $arg2);
  return/*_void*/;
} // end-of-function


function
ats2phppre_arrszref_make_elt($arg0, $arg1)
{
//
  $tmpret3 = NULL;
  $tmp4 = NULL;
//
  __patsflab_arrszref_make_elt:
  $tmp4 = ats2phppre_arrayref_make_elt($arg0, $arg1);
  $tmpret3 = ats2phppre_arrszref_make_arrayref($tmp4, $arg0);
  return $tmpret3;
} // end-of-function


function
ats2phppre_arrszref_exists_cloref($arg0, $arg1)
{
//
  $tmpret5 = NULL;
  $tmp6 = NULL;
//
  __patsflab_arrszref_exists_cloref:
  $tmp6 = ats2phppre_arrszref_size($arg0);
  $tmpret5 = ats2phppre_int_exists_cloref($tmp6, $arg1);
  return $tmpret5;
} // end-of-function


function
ats2phppre_arrszref_forall_cloref($arg0, $arg1)
{
//
  $tmpret7 = NULL;
  $tmp8 = NULL;
//
  __patsflab_arrszref_forall_cloref:
  $tmp8 = ats2phppre_arrszref_size($arg0);
  $tmpret7 = ats2phppre_int_forall_cloref($tmp8, $arg1);
  return $tmpret7;
} // end-of-function


function
ats2phppre_arrszref_foreach_cloref($arg0, $arg1)
{
//
  $tmp10 = NULL;
//
  __patsflab_arrszref_foreach_cloref:
  $tmp10 = ats2phppre_arrszref_size($arg0);
  ats2phppre_int_foreach_cloref($tmp10, $arg1);
  return/*_void*/;
} // end-of-function


function
ats2phppre_arrszref_foreach_method($arg0)
{
//
  $tmpret11 = NULL;
//
  __patsflab_arrszref_foreach_method:
  $tmpret11 = _ats2phppre_arrayref_patsfun_8__closurerize($arg0);
  return $tmpret11;
} // end-of-function


function
_ats2phppre_arrayref_patsfun_8($env0, $arg0)
{
//
//
  __patsflab__ats2phppre_arrayref_patsfun_8:
  ats2phppre_arrszref_foreach_cloref($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ats2phppre_arrayref_make_elt($arg0, $arg1)
{
//
  $tmpret13 = NULL;
  $tmp14 = NULL;
//
  __patsflab_arrayref_make_elt:
  $tmp14 = ats2phppre_PHParref_make_elt($arg0, $arg1);
  $tmpret13 = $tmp14;
  return $tmpret13;
} // end-of-function


function
ats2phppre_arrayref_get_at($arg0, $arg1)
{
//
  $tmpret15 = NULL;
//
  __patsflab_arrayref_get_at:
  $tmpret15 = ats2phppre_PHParref_get_at($arg0, $arg1);
  return $tmpret15;
} // end-of-function


function
ats2phppre_arrayref_set_at($arg0, $arg1, $arg2)
{
//
//
  __patsflab_arrayref_set_at:
  ats2phppre_PHParref_set_at($arg0, $arg1, $arg2);
  return/*_void*/;
} // end-of-function


function
ats2phppre_arrszref_make_arrayref($arg0, $arg1)
{
//
  $tmpret17 = NULL;
//
  __patsflab_arrszref_make_arrayref:
  $tmpret17 = $arg0;
  return $tmpret17;
} // end-of-function


function
ats2phppre_arrszref_size($arg0)
{
//
  $tmpret18 = NULL;
//
  __patsflab_arrszref_size:
  $tmpret18 = ats2phppre_PHParref_length($arg0);
  return $tmpret18;
} // end-of-function


function
ats2phppre_arrszref_get_at($arg0, $arg1)
{
//
  $tmpret19 = NULL;
//
  __patsflab_arrszref_get_at:
  $tmpret19 = ats2phppre_PHParref_get_at($arg0, $arg1);
  return $tmpret19;
} // end-of-function


function
ats2phppre_arrszref_set_at($arg0, $arg1, $arg2)
{
//
//
  __patsflab_arrszref_set_at:
  ats2phppre_PHParref_set_at($arg0, $arg1, $arg2);
  return/*_void*/;
} // end-of-function

/* ****** ****** */

/* end-of-compilation-unit */
?>
