<?php
/*
**
** The PHP code is generated by atscc2php
** The starting compilation time is: 2016-12-19:  0h:23m
**
*/
function
_ats2phppre_list_patsfun_31__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_list_patsfun_31($cenv[1], $arg0); }, $env0);
}

function
_ats2phppre_list_patsfun_35__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_list_patsfun_35($cenv[1], $arg0); }, $env0);
}

function
_ats2phppre_list_patsfun_38__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_list_patsfun_38($cenv[1], $arg0); }, $env0);
}

function
_ats2phppre_list_patsfun_42__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_list_patsfun_42($cenv[1], $arg0); }, $env0);
}

function
_ats2phppre_list_patsfun_46__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_list_patsfun_46($cenv[1], $arg0); }, $env0);
}

function
_ats2phppre_list_patsfun_50__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_list_patsfun_50($cenv[1], $arg0); }, $env0);
}

function
_ats2phppre_list_patsfun_53__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_list_patsfun_53($cenv[1], $arg0); }, $env0);
}

function
_ats2phppre_list_patsfun_57__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_list_patsfun_57($cenv[1], $arg0); }, $env0);
}

function
_ats2phppre_list_patsfun_61__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_list_patsfun_61($cenv[1], $arg0); }, $env0);
}

function
_ats2phppre_list_patsfun_65__closurerize($env0, $env1)
{
  return array(function($cenv, $arg0) { return _ats2phppre_list_patsfun_65($cenv[1], $cenv[2], $arg0); }, $env0, $env1);
}

function
_ats2phppre_list_patsfun_69__closurerize($env0, $env1)
{
  return array(function($cenv, $arg0) { return _ats2phppre_list_patsfun_69($cenv[1], $cenv[2], $arg0); }, $env0, $env1);
}

function
_ats2phppre_list_patsfun_73__closurerize($env0, $env1)
{
  return array(function($cenv, $arg0) { return _ats2phppre_list_patsfun_73($cenv[1], $cenv[2], $arg0); }, $env0, $env1);
}

function
_ats2phppre_list_patsfun_77__closurerize($env0, $env1)
{
  return array(function($cenv, $arg0) { return _ats2phppre_list_patsfun_77($cenv[1], $cenv[2], $arg0); }, $env0, $env1);
}

function
_ats2phppre_list_patsfun_82__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_list_patsfun_82($cenv[1], $arg0); }, $env0);
}

function
_ats2phppre_list_patsfun_85__closurerize($env0, $env1)
{
  return array(function($cenv, $arg0) { return _ats2phppre_list_patsfun_85($cenv[1], $cenv[2], $arg0); }, $env0, $env1);
}

function
_ats2phppre_list_patsfun_88__closurerize($env0, $env1)
{
  return array(function($cenv, $arg0) { return _ats2phppre_list_patsfun_88($cenv[1], $cenv[2], $arg0); }, $env0, $env1);
}

function
_ats2phppre_list_patsfun_90__closurerize($env0, $env1)
{
  return array(function($cenv, $arg0) { return _ats2phppre_list_patsfun_90($cenv[1], $cenv[2], $arg0); }, $env0, $env1);
}


function
ats2phppre_list_make_intrange_2($arg0, $arg1)
{
//
  $tmpret2 = NULL;
//
  __patsflab_list_make_intrange_2:
  $tmpret2 = ats2phppre_list_make_intrange_3($arg0, $arg1, 1);
  return $tmpret2;
} // end-of-function


function
ats2phppre_list_make_intrange_3($arg0, $arg1, $arg2)
{
//
  $tmpret3 = NULL;
  $tmp14 = NULL;
  $tmp15 = NULL;
  $tmp16 = NULL;
  $tmp17 = NULL;
  $tmp18 = NULL;
  $tmp19 = NULL;
  $tmp20 = NULL;
  $tmp21 = NULL;
  $tmp22 = NULL;
  $tmp23 = NULL;
  $tmp24 = NULL;
  $tmp25 = NULL;
  $tmp26 = NULL;
  $tmp27 = NULL;
  $tmp28 = NULL;
  $tmp29 = NULL;
  $tmp30 = NULL;
  $tmp31 = NULL;
  $tmp32 = NULL;
  $tmp33 = NULL;
  $tmp34 = NULL;
//
  __patsflab_list_make_intrange_3:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab6:
    $tmp14 = ats2phppre_gt_int0_int0($arg2, 0);
    if(!ATSCKpat_bool($tmp14, true)) goto __atstmplab7;
    $tmp15 = ats2phppre_lt_int0_int0($arg0, $arg1);
    if($tmp15) {
      $tmp19 = ats2phppre_sub_int0_int0($arg1, $arg0);
      $tmp18 = ats2phppre_add_int0_int0($tmp19, $arg2);
      $tmp17 = ats2phppre_sub_int0_int0($tmp18, 1);
      $tmp16 = ats2phppre_div_int0_int0($tmp17, $arg2);
      $tmp22 = ats2phppre_sub_int0_int0($tmp16, 1);
      $tmp21 = ats2phppre_mul_int0_int0($tmp22, $arg2);
      $tmp20 = ats2phppre_add_int0_int0($arg0, $tmp21);
      $tmp23 = NULL;
      $tmpret3 = _ats2phppre_list_loop1_4($tmp16, $tmp20, $arg2, $tmp23);
    } else {
      $tmpret3 = NULL;
    } // endif
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab7:
    $tmp24 = ats2phppre_lt_int0_int0($arg2, 0);
    if(!ATSCKpat_bool($tmp24, true)) goto __atstmplab8;
    $tmp25 = ats2phppre_gt_int0_int0($arg0, $arg1);
    if($tmp25) {
      $tmp26 = ats2phppre_neg_int0($arg2);
      $tmp30 = ats2phppre_sub_int0_int0($arg0, $arg1);
      $tmp29 = ats2phppre_add_int0_int0($tmp30, $tmp26);
      $tmp28 = ats2phppre_sub_int0_int0($tmp29, 1);
      $tmp27 = ats2phppre_div_int0_int0($tmp28, $tmp26);
      $tmp33 = ats2phppre_sub_int0_int0($tmp27, 1);
      $tmp32 = ats2phppre_mul_int0_int0($tmp33, $tmp26);
      $tmp31 = ats2phppre_sub_int0_int0($arg0, $tmp32);
      $tmp34 = NULL;
      $tmpret3 = _ats2phppre_list_loop2_5($tmp27, $tmp31, $tmp26, $tmp34);
    } else {
      $tmpret3 = NULL;
    } // endif
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab8:
    $tmpret3 = NULL;
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret3;
} // end-of-function


function
_ats2phppre_list_loop1_4($arg0, $arg1, $arg2, $arg3)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $apy2 = NULL;
  $apy3 = NULL;
  $tmpret4 = NULL;
  $tmp5 = NULL;
  $tmp6 = NULL;
  $tmp7 = NULL;
  $tmp8 = NULL;
//
  __patsflab__ats2phppre_list_loop1_4:
  $tmp5 = ats2phppre_gt_int0_int0($arg0, 0);
  if($tmp5) {
    $tmp6 = ats2phppre_sub_int0_int0($arg0, 1);
    $tmp7 = ats2phppre_sub_int0_int0($arg1, $arg2);
    $tmp8 = array($arg1, $arg3);
    // ATStailcalseq_beg
    $apy0 = $tmp6;
    $apy1 = $tmp7;
    $apy2 = $arg2;
    $apy3 = $tmp8;
    $arg0 = $apy0;
    $arg1 = $apy1;
    $arg2 = $apy2;
    $arg3 = $apy3;
    goto __patsflab__ats2phppre_list_loop1_4;
    // ATStailcalseq_end
  } else {
    $tmpret4 = $arg3;
  } // endif
  return $tmpret4;
} // end-of-function


function
_ats2phppre_list_loop2_5($arg0, $arg1, $arg2, $arg3)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $apy2 = NULL;
  $apy3 = NULL;
  $tmpret9 = NULL;
  $tmp10 = NULL;
  $tmp11 = NULL;
  $tmp12 = NULL;
  $tmp13 = NULL;
//
  __patsflab__ats2phppre_list_loop2_5:
  $tmp10 = ats2phppre_gt_int0_int0($arg0, 0);
  if($tmp10) {
    $tmp11 = ats2phppre_sub_int0_int0($arg0, 1);
    $tmp12 = ats2phppre_add_int0_int0($arg1, $arg2);
    $tmp13 = array($arg1, $arg3);
    // ATStailcalseq_beg
    $apy0 = $tmp11;
    $apy1 = $tmp12;
    $apy2 = $arg2;
    $apy3 = $tmp13;
    $arg0 = $apy0;
    $arg1 = $apy1;
    $arg2 = $apy2;
    $arg3 = $apy3;
    goto __patsflab__ats2phppre_list_loop2_5;
    // ATStailcalseq_end
  } else {
    $tmpret9 = $arg3;
  } // endif
  return $tmpret9;
} // end-of-function


function
ats2phppre_list_length($arg0)
{
//
  $tmpret46 = NULL;
//
  __patsflab_list_length:
  $tmpret46 = _ats2phppre_list_loop_12($arg0, 0);
  return $tmpret46;
} // end-of-function


function
_ats2phppre_list_loop_12($arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmpret47 = NULL;
  $tmp49 = NULL;
  $tmp50 = NULL;
//
  __patsflab__ats2phppre_list_loop_12:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab13:
    if(ATSCKptriscons($arg0)) goto __atstmplab16;
    __atstmplab14:
    $tmpret47 = $arg1;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab15:
    __atstmplab16:
    $tmp49 = $arg0[1];
    $tmp50 = ats2phppre_add_int1_int1($arg1, 1);
    // ATStailcalseq_beg
    $apy0 = $tmp49;
    $apy1 = $tmp50;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab__ats2phppre_list_loop_12;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret47;
} // end-of-function


function
ats2phppre_list_last($arg0)
{
//
  $apy0 = NULL;
  $tmpret51 = NULL;
  $tmp52 = NULL;
  $tmp53 = NULL;
//
  __patsflab_list_last:
  $tmp52 = $arg0[0];
  $tmp53 = $arg0[1];
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab17:
    if(ATSCKptriscons($tmp53)) goto __atstmplab20;
    __atstmplab18:
    $tmpret51 = $tmp52;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab19:
    __atstmplab20:
    // ATStailcalseq_beg
    $apy0 = $tmp53;
    $arg0 = $apy0;
    goto __patsflab_list_last;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret51;
} // end-of-function


function
ats2phppre_list_get_at($arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmpret54 = NULL;
  $tmp55 = NULL;
  $tmp56 = NULL;
  $tmp57 = NULL;
  $tmp58 = NULL;
//
  __patsflab_list_get_at:
  $tmp55 = ats2phppre_eq_int1_int1($arg1, 0);
  if($tmp55) {
    $tmp56 = $arg0[0];
    $tmpret54 = $tmp56;
  } else {
    $tmp57 = $arg0[1];
    $tmp58 = ats2phppre_sub_int1_int1($arg1, 1);
    // ATStailcalseq_beg
    $apy0 = $tmp57;
    $apy1 = $tmp58;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab_list_get_at;
    // ATStailcalseq_end
  } // endif
  return $tmpret54;
} // end-of-function


function
ats2phppre_list_snoc($arg0, $arg1)
{
//
  $tmpret59 = NULL;
  $tmp60 = NULL;
  $tmp61 = NULL;
//
  __patsflab_list_snoc:
  $tmp61 = NULL;
  $tmp60 = array($arg1, $tmp61);
  $tmpret59 = ats2phppre_list_append($arg0, $tmp60);
  return $tmpret59;
} // end-of-function


function
ats2phppre_list_extend($arg0, $arg1)
{
//
  $tmpret62 = NULL;
  $tmp63 = NULL;
  $tmp64 = NULL;
//
  __patsflab_list_extend:
  $tmp64 = NULL;
  $tmp63 = array($arg1, $tmp64);
  $tmpret62 = ats2phppre_list_append($arg0, $tmp63);
  return $tmpret62;
} // end-of-function


function
ats2phppre_list_append($arg0, $arg1)
{
//
  $tmpret65 = NULL;
  $tmp66 = NULL;
  $tmp67 = NULL;
  $tmp68 = NULL;
//
  __patsflab_list_append:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab21:
    if(ATSCKptriscons($arg0)) goto __atstmplab24;
    __atstmplab22:
    $tmpret65 = $arg1;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab23:
    __atstmplab24:
    $tmp66 = $arg0[0];
    $tmp67 = $arg0[1];
    $tmp68 = ats2phppre_list_append($tmp67, $arg1);
    $tmpret65 = array($tmp66, $tmp68);
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret65;
} // end-of-function


function
ats2phppre_list_reverse($arg0)
{
//
  $tmpret69 = NULL;
  $tmp70 = NULL;
//
  __patsflab_list_reverse:
  $tmp70 = NULL;
  $tmpret69 = ats2phppre_list_reverse_append($arg0, $tmp70);
  return $tmpret69;
} // end-of-function


function
ats2phppre_list_reverse_append($arg0, $arg1)
{
//
  $tmpret71 = NULL;
//
  __patsflab_list_reverse_append:
  $tmpret71 = _ats2phppre_list_loop_20($arg0, $arg1);
  return $tmpret71;
} // end-of-function


function
_ats2phppre_list_loop_20($arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmpret72 = NULL;
  $tmp73 = NULL;
  $tmp74 = NULL;
  $tmp75 = NULL;
//
  __patsflab__ats2phppre_list_loop_20:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab25:
    if(ATSCKptriscons($arg0)) goto __atstmplab28;
    __atstmplab26:
    $tmpret72 = $arg1;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab27:
    __atstmplab28:
    $tmp73 = $arg0[0];
    $tmp74 = $arg0[1];
    $tmp75 = array($tmp73, $arg1);
    // ATStailcalseq_beg
    $apy0 = $tmp74;
    $apy1 = $tmp75;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab__ats2phppre_list_loop_20;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret72;
} // end-of-function


function
ats2phppre_list_concat($arg0)
{
//
  $tmpret76 = NULL;
//
  __patsflab_list_concat:
  $tmpret76 = _ats2phppre_list_auxlst_22($arg0);
  return $tmpret76;
} // end-of-function


function
_ats2phppre_list_auxlst_22($arg0)
{
//
  $tmpret77 = NULL;
  $tmp78 = NULL;
  $tmp79 = NULL;
  $tmp80 = NULL;
//
  __patsflab__ats2phppre_list_auxlst_22:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab29:
    if(ATSCKptriscons($arg0)) goto __atstmplab32;
    __atstmplab30:
    $tmpret77 = NULL;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab31:
    __atstmplab32:
    $tmp78 = $arg0[0];
    $tmp79 = $arg0[1];
    $tmp80 = _ats2phppre_list_auxlst_22($tmp79);
    $tmpret77 = ats2phppre_list_append($tmp78, $tmp80);
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret77;
} // end-of-function


function
ats2phppre_list_take($arg0, $arg1)
{
//
  $tmpret81 = NULL;
  $tmp82 = NULL;
  $tmp83 = NULL;
  $tmp84 = NULL;
  $tmp85 = NULL;
  $tmp86 = NULL;
//
  __patsflab_list_take:
  $tmp82 = ats2phppre_gt_int1_int1($arg1, 0);
  if($tmp82) {
    $tmp83 = $arg0[0];
    $tmp84 = $arg0[1];
    $tmp86 = ats2phppre_sub_int1_int1($arg1, 1);
    $tmp85 = ats2phppre_list_take($tmp84, $tmp86);
    $tmpret81 = array($tmp83, $tmp85);
  } else {
    $tmpret81 = NULL;
  } // endif
  return $tmpret81;
} // end-of-function


function
ats2phppre_list_drop($arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmpret87 = NULL;
  $tmp88 = NULL;
  $tmp89 = NULL;
  $tmp90 = NULL;
//
  __patsflab_list_drop:
  $tmp88 = ats2phppre_gt_int1_int1($arg1, 0);
  if($tmp88) {
    $tmp89 = $arg0[1];
    $tmp90 = ats2phppre_sub_int1_int1($arg1, 1);
    // ATStailcalseq_beg
    $apy0 = $tmp89;
    $apy1 = $tmp90;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab_list_drop;
    // ATStailcalseq_end
  } else {
    $tmpret87 = $arg0;
  } // endif
  return $tmpret87;
} // end-of-function


function
ats2phppre_list_split_at($arg0, $arg1)
{
//
  $tmpret91 = NULL;
  $tmp92 = NULL;
  $tmp93 = NULL;
//
  __patsflab_list_split_at:
  $tmp92 = ats2phppre_list_take($arg0, $arg1);
  $tmp93 = ats2phppre_list_drop($arg0, $arg1);
  $tmpret91 = array($tmp92, $tmp93);
  return $tmpret91;
} // end-of-function


function
ats2phppre_list_insert_at($arg0, $arg1, $arg2)
{
//
  $tmpret94 = NULL;
  $tmp95 = NULL;
  $tmp96 = NULL;
  $tmp97 = NULL;
  $tmp98 = NULL;
  $tmp99 = NULL;
//
  __patsflab_list_insert_at:
  $tmp95 = ats2phppre_gt_int1_int1($arg1, 0);
  if($tmp95) {
    $tmp96 = $arg0[0];
    $tmp97 = $arg0[1];
    $tmp99 = ats2phppre_sub_int1_int1($arg1, 1);
    $tmp98 = ats2phppre_list_insert_at($tmp97, $tmp99, $arg2);
    $tmpret94 = array($tmp96, $tmp98);
  } else {
    $tmpret94 = array($arg2, $arg0);
  } // endif
  return $tmpret94;
} // end-of-function


function
ats2phppre_list_remove_at($arg0, $arg1)
{
//
  $tmpret100 = NULL;
  $tmp101 = NULL;
  $tmp102 = NULL;
  $tmp103 = NULL;
  $tmp104 = NULL;
  $tmp105 = NULL;
//
  __patsflab_list_remove_at:
  $tmp101 = $arg0[0];
  $tmp102 = $arg0[1];
  $tmp103 = ats2phppre_gt_int1_int1($arg1, 0);
  if($tmp103) {
    $tmp105 = ats2phppre_sub_int1_int1($arg1, 1);
    $tmp104 = ats2phppre_list_remove_at($tmp102, $tmp105);
    $tmpret100 = array($tmp101, $tmp104);
  } else {
    $tmpret100 = $tmp102;
  } // endif
  return $tmpret100;
} // end-of-function


function
ats2phppre_list_takeout_at($arg0, $arg1)
{
//
  $tmpret106 = NULL;
  $tmp107 = NULL;
  $tmp108 = NULL;
  $tmp109 = NULL;
  $tmp110 = NULL;
  $tmp111 = NULL;
  $tmp112 = NULL;
  $tmp113 = NULL;
  $tmp114 = NULL;
//
  __patsflab_list_takeout_at:
  $tmp107 = $arg0[0];
  $tmp108 = $arg0[1];
  $tmp109 = ats2phppre_gt_int1_int1($arg1, 0);
  if($tmp109) {
    $tmp111 = ats2phppre_sub_int1_int1($arg1, 1);
    $tmp110 = ats2phppre_list_takeout_at($tmp108, $tmp111);
    $tmp112 = $tmp110[0];
    $tmp113 = $tmp110[1];
    $tmp114 = array($tmp107, $tmp113);
    $tmpret106 = array($tmp112, $tmp114);
  } else {
    $tmpret106 = array($tmp107, $tmp108);
  } // endif
  return $tmpret106;
} // end-of-function


function
ats2phppre_list_exists($arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmpret115 = NULL;
  $tmp116 = NULL;
  $tmp117 = NULL;
  $tmp118 = NULL;
//
  __patsflab_list_exists:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab33:
    if(ATSCKptriscons($arg0)) goto __atstmplab36;
    __atstmplab34:
    $tmpret115 = false;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab35:
    __atstmplab36:
    $tmp116 = $arg0[0];
    $tmp117 = $arg0[1];
    $tmp118 = $arg1[0]($arg1, $tmp116);
    if($tmp118) {
      $tmpret115 = true;
    } else {
      // ATStailcalseq_beg
      $apy0 = $tmp117;
      $apy1 = $arg1;
      $arg0 = $apy0;
      $arg1 = $apy1;
      goto __patsflab_list_exists;
      // ATStailcalseq_end
    } // endif
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret115;
} // end-of-function


function
ats2phppre_list_exists_method($arg0)
{
//
  $tmpret119 = NULL;
//
  __patsflab_list_exists_method:
  $tmpret119 = _ats2phppre_list_patsfun_31__closurerize($arg0);
  return $tmpret119;
} // end-of-function


function
_ats2phppre_list_patsfun_31($env0, $arg0)
{
//
  $tmpret120 = NULL;
//
  __patsflab__ats2phppre_list_patsfun_31:
  $tmpret120 = ats2phppre_list_exists($env0, $arg0);
  return $tmpret120;
} // end-of-function


function
ats2phppre_list_iexists($arg0, $arg1)
{
//
  $tmpret121 = NULL;
//
  __patsflab_list_iexists:
  $tmpret121 = _ats2phppre_list_loop_33($arg1, 0, $arg0);
  return $tmpret121;
} // end-of-function


function
_ats2phppre_list_loop_33($env0, $arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmpret122 = NULL;
  $tmp123 = NULL;
  $tmp124 = NULL;
  $tmp125 = NULL;
  $tmp126 = NULL;
//
  __patsflab__ats2phppre_list_loop_33:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab37:
    if(ATSCKptriscons($arg1)) goto __atstmplab40;
    __atstmplab38:
    $tmpret122 = false;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab39:
    __atstmplab40:
    $tmp123 = $arg1[0];
    $tmp124 = $arg1[1];
    $tmp125 = $env0[0]($env0, $arg0, $tmp123);
    if($tmp125) {
      $tmpret122 = true;
    } else {
      $tmp126 = ats2phppre_add_int1_int1($arg0, 1);
      // ATStailcalseq_beg
      $apy0 = $tmp126;
      $apy1 = $tmp124;
      $arg0 = $apy0;
      $arg1 = $apy1;
      goto __patsflab__ats2phppre_list_loop_33;
      // ATStailcalseq_end
    } // endif
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret122;
} // end-of-function


function
ats2phppre_list_iexists_method($arg0)
{
//
  $tmpret127 = NULL;
//
  __patsflab_list_iexists_method:
  $tmpret127 = _ats2phppre_list_patsfun_35__closurerize($arg0);
  return $tmpret127;
} // end-of-function


function
_ats2phppre_list_patsfun_35($env0, $arg0)
{
//
  $tmpret128 = NULL;
//
  __patsflab__ats2phppre_list_patsfun_35:
  $tmpret128 = ats2phppre_list_iexists($env0, $arg0);
  return $tmpret128;
} // end-of-function


function
ats2phppre_list_forall($arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmpret129 = NULL;
  $tmp130 = NULL;
  $tmp131 = NULL;
  $tmp132 = NULL;
//
  __patsflab_list_forall:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab41:
    if(ATSCKptriscons($arg0)) goto __atstmplab44;
    __atstmplab42:
    $tmpret129 = true;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab43:
    __atstmplab44:
    $tmp130 = $arg0[0];
    $tmp131 = $arg0[1];
    $tmp132 = $arg1[0]($arg1, $tmp130);
    if($tmp132) {
      // ATStailcalseq_beg
      $apy0 = $tmp131;
      $apy1 = $arg1;
      $arg0 = $apy0;
      $arg1 = $apy1;
      goto __patsflab_list_forall;
      // ATStailcalseq_end
    } else {
      $tmpret129 = false;
    } // endif
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret129;
} // end-of-function


function
ats2phppre_list_forall_method($arg0)
{
//
  $tmpret133 = NULL;
//
  __patsflab_list_forall_method:
  $tmpret133 = _ats2phppre_list_patsfun_38__closurerize($arg0);
  return $tmpret133;
} // end-of-function


function
_ats2phppre_list_patsfun_38($env0, $arg0)
{
//
  $tmpret134 = NULL;
//
  __patsflab__ats2phppre_list_patsfun_38:
  $tmpret134 = ats2phppre_list_forall($env0, $arg0);
  return $tmpret134;
} // end-of-function


function
ats2phppre_list_iforall($arg0, $arg1)
{
//
  $tmpret135 = NULL;
//
  __patsflab_list_iforall:
  $tmpret135 = _ats2phppre_list_loop_40($arg1, 0, $arg0);
  return $tmpret135;
} // end-of-function


function
_ats2phppre_list_loop_40($env0, $arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmpret136 = NULL;
  $tmp137 = NULL;
  $tmp138 = NULL;
  $tmp139 = NULL;
  $tmp140 = NULL;
//
  __patsflab__ats2phppre_list_loop_40:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab45:
    if(ATSCKptriscons($arg1)) goto __atstmplab48;
    __atstmplab46:
    $tmpret136 = true;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab47:
    __atstmplab48:
    $tmp137 = $arg1[0];
    $tmp138 = $arg1[1];
    $tmp139 = $env0[0]($env0, $arg0, $tmp137);
    if($tmp139) {
      $tmp140 = ats2phppre_add_int1_int1($arg0, 1);
      // ATStailcalseq_beg
      $apy0 = $tmp140;
      $apy1 = $tmp138;
      $arg0 = $apy0;
      $arg1 = $apy1;
      goto __patsflab__ats2phppre_list_loop_40;
      // ATStailcalseq_end
    } else {
      $tmpret136 = false;
    } // endif
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret136;
} // end-of-function


function
ats2phppre_list_iforall_method($arg0)
{
//
  $tmpret141 = NULL;
//
  __patsflab_list_iforall_method:
  $tmpret141 = _ats2phppre_list_patsfun_42__closurerize($arg0);
  return $tmpret141;
} // end-of-function


function
_ats2phppre_list_patsfun_42($env0, $arg0)
{
//
  $tmpret142 = NULL;
//
  __patsflab__ats2phppre_list_patsfun_42:
  $tmpret142 = ats2phppre_list_iforall($env0, $arg0);
  return $tmpret142;
} // end-of-function


function
ats2phppre_list_app($arg0, $arg1)
{
//
//
  __patsflab_list_app:
  ats2phppre_list_foreach($arg0, $arg1);
  return/*_void*/;
} // end-of-function


function
ats2phppre_list_foreach($arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmp145 = NULL;
  $tmp146 = NULL;
//
  __patsflab_list_foreach:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab49:
    if(ATSCKptriscons($arg0)) goto __atstmplab52;
    __atstmplab50:
    // ATSINSmove_void;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab51:
    __atstmplab52:
    $tmp145 = $arg0[0];
    $tmp146 = $arg0[1];
    $arg1[0]($arg1, $tmp145);
    // ATStailcalseq_beg
    $apy0 = $tmp146;
    $apy1 = $arg1;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab_list_foreach;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
ats2phppre_list_foreach_method($arg0)
{
//
  $tmpret148 = NULL;
//
  __patsflab_list_foreach_method:
  $tmpret148 = _ats2phppre_list_patsfun_46__closurerize($arg0);
  return $tmpret148;
} // end-of-function


function
_ats2phppre_list_patsfun_46($env0, $arg0)
{
//
//
  __patsflab__ats2phppre_list_patsfun_46:
  ats2phppre_list_foreach($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ats2phppre_list_iforeach($arg0, $arg1)
{
//
//
  __patsflab_list_iforeach:
  _ats2phppre_list_aux_48($arg1, 0, $arg0);
  return/*_void*/;
} // end-of-function


function
_ats2phppre_list_aux_48($env0, $arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmp152 = NULL;
  $tmp153 = NULL;
  $tmp155 = NULL;
//
  __patsflab__ats2phppre_list_aux_48:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab53:
    if(ATSCKptriscons($arg1)) goto __atstmplab56;
    __atstmplab54:
    // ATSINSmove_void;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab55:
    __atstmplab56:
    $tmp152 = $arg1[0];
    $tmp153 = $arg1[1];
    $env0[0]($env0, $arg0, $tmp152);
    $tmp155 = ats2phppre_add_int1_int1($arg0, 1);
    // ATStailcalseq_beg
    $apy0 = $tmp155;
    $apy1 = $tmp153;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab__ats2phppre_list_aux_48;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
ats2phppre_list_iforeach_method($arg0)
{
//
  $tmpret156 = NULL;
//
  __patsflab_list_iforeach_method:
  $tmpret156 = _ats2phppre_list_patsfun_50__closurerize($arg0);
  return $tmpret156;
} // end-of-function


function
_ats2phppre_list_patsfun_50($env0, $arg0)
{
//
//
  __patsflab__ats2phppre_list_patsfun_50:
  ats2phppre_list_iforeach($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ats2phppre_list_rforeach($arg0, $arg1)
{
//
  $tmp159 = NULL;
  $tmp160 = NULL;
//
  __patsflab_list_rforeach:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab57:
    if(ATSCKptriscons($arg0)) goto __atstmplab60;
    __atstmplab58:
    // ATSINSmove_void;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab59:
    __atstmplab60:
    $tmp159 = $arg0[0];
    $tmp160 = $arg0[1];
    ats2phppre_list_rforeach($tmp160, $arg1);
    $arg1[0]($arg1, $tmp159);
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
ats2phppre_list_rforeach_method($arg0)
{
//
  $tmpret162 = NULL;
//
  __patsflab_list_rforeach_method:
  $tmpret162 = _ats2phppre_list_patsfun_53__closurerize($arg0);
  return $tmpret162;
} // end-of-function


function
_ats2phppre_list_patsfun_53($env0, $arg0)
{
//
//
  __patsflab__ats2phppre_list_patsfun_53:
  ats2phppre_list_rforeach($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ats2phppre_list_filter($arg0, $arg1)
{
//
  $tmpret164 = NULL;
//
  __patsflab_list_filter:
  $tmpret164 = _ats2phppre_list_aux_55($arg1, $arg0);
  return $tmpret164;
} // end-of-function


function
_ats2phppre_list_aux_55($env0, $arg0)
{
//
  $apy0 = NULL;
  $tmpret165 = NULL;
  $tmp166 = NULL;
  $tmp167 = NULL;
  $tmp168 = NULL;
  $tmp169 = NULL;
//
  __patsflab__ats2phppre_list_aux_55:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab61:
    if(ATSCKptriscons($arg0)) goto __atstmplab64;
    __atstmplab62:
    $tmpret165 = NULL;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab63:
    __atstmplab64:
    $tmp166 = $arg0[0];
    $tmp167 = $arg0[1];
    $tmp168 = $env0[0]($env0, $tmp166);
    if($tmp168) {
      $tmp169 = _ats2phppre_list_aux_55($env0, $tmp167);
      $tmpret165 = array($tmp166, $tmp169);
    } else {
      // ATStailcalseq_beg
      $apy0 = $tmp167;
      $arg0 = $apy0;
      goto __patsflab__ats2phppre_list_aux_55;
      // ATStailcalseq_end
    } // endif
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret165;
} // end-of-function


function
ats2phppre_list_filter_method($arg0)
{
//
  $tmpret170 = NULL;
//
  __patsflab_list_filter_method:
  $tmpret170 = _ats2phppre_list_patsfun_57__closurerize($arg0);
  return $tmpret170;
} // end-of-function


function
_ats2phppre_list_patsfun_57($env0, $arg0)
{
//
  $tmpret171 = NULL;
//
  __patsflab__ats2phppre_list_patsfun_57:
  $tmpret171 = ats2phppre_list_filter($env0, $arg0);
  return $tmpret171;
} // end-of-function


function
ats2phppre_list_map($arg0, $arg1)
{
//
  $tmpret172 = NULL;
//
  __patsflab_list_map:
  $tmpret172 = _ats2phppre_list_aux_59($arg1, $arg0);
  return $tmpret172;
} // end-of-function


function
_ats2phppre_list_aux_59($env0, $arg0)
{
//
  $tmpret173 = NULL;
  $tmp174 = NULL;
  $tmp175 = NULL;
  $tmp176 = NULL;
  $tmp177 = NULL;
//
  __patsflab__ats2phppre_list_aux_59:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab65:
    if(ATSCKptriscons($arg0)) goto __atstmplab68;
    __atstmplab66:
    $tmpret173 = NULL;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab67:
    __atstmplab68:
    $tmp174 = $arg0[0];
    $tmp175 = $arg0[1];
    $tmp176 = $env0[0]($env0, $tmp174);
    $tmp177 = _ats2phppre_list_aux_59($env0, $tmp175);
    $tmpret173 = array($tmp176, $tmp177);
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret173;
} // end-of-function


function
ats2phppre_list_map_method($arg0, $arg1)
{
//
  $tmpret178 = NULL;
//
  __patsflab_list_map_method:
  $tmpret178 = _ats2phppre_list_patsfun_61__closurerize($arg0);
  return $tmpret178;
} // end-of-function


function
_ats2phppre_list_patsfun_61($env0, $arg0)
{
//
  $tmpret179 = NULL;
//
  __patsflab__ats2phppre_list_patsfun_61:
  $tmpret179 = ats2phppre_list_map($env0, $arg0);
  return $tmpret179;
} // end-of-function


function
ats2phppre_list_foldleft($arg0, $arg1, $arg2)
{
//
  $tmpret180 = NULL;
//
  __patsflab_list_foldleft:
  $tmpret180 = _ats2phppre_list_loop_63($arg2, $arg1, $arg0);
  return $tmpret180;
} // end-of-function


function
_ats2phppre_list_loop_63($env0, $arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmpret181 = NULL;
  $tmp182 = NULL;
  $tmp183 = NULL;
  $tmp184 = NULL;
//
  __patsflab__ats2phppre_list_loop_63:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab69:
    if(ATSCKptriscons($arg1)) goto __atstmplab72;
    __atstmplab70:
    $tmpret181 = $arg0;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab71:
    __atstmplab72:
    $tmp182 = $arg1[0];
    $tmp183 = $arg1[1];
    $tmp184 = $env0[0]($env0, $arg0, $tmp182);
    // ATStailcalseq_beg
    $apy0 = $tmp184;
    $apy1 = $tmp183;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab__ats2phppre_list_loop_63;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret181;
} // end-of-function


function
ats2phppre_list_foldleft_method($arg0, $arg1)
{
//
  $tmpret185 = NULL;
//
  __patsflab_list_foldleft_method:
  $tmpret185 = _ats2phppre_list_patsfun_65__closurerize($arg0, $arg1);
  return $tmpret185;
} // end-of-function


function
_ats2phppre_list_patsfun_65($env0, $env1, $arg0)
{
//
  $tmpret186 = NULL;
//
  __patsflab__ats2phppre_list_patsfun_65:
  $tmpret186 = ats2phppre_list_foldleft($env0, $env1, $arg0);
  return $tmpret186;
} // end-of-function


function
ats2phppre_list_ifoldleft($arg0, $arg1, $arg2)
{
//
  $tmpret187 = NULL;
//
  __patsflab_list_ifoldleft:
  $tmpret187 = _ats2phppre_list_loop_67($arg2, 0, $arg1, $arg0);
  return $tmpret187;
} // end-of-function


function
_ats2phppre_list_loop_67($env0, $arg0, $arg1, $arg2)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $apy2 = NULL;
  $tmpret188 = NULL;
  $tmp189 = NULL;
  $tmp190 = NULL;
  $tmp191 = NULL;
  $tmp192 = NULL;
//
  __patsflab__ats2phppre_list_loop_67:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab73:
    if(ATSCKptriscons($arg2)) goto __atstmplab76;
    __atstmplab74:
    $tmpret188 = $arg1;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab75:
    __atstmplab76:
    $tmp189 = $arg2[0];
    $tmp190 = $arg2[1];
    $tmp191 = ats2phppre_add_int1_int1($arg0, 1);
    $tmp192 = $env0[0]($env0, $arg0, $arg1, $tmp189);
    // ATStailcalseq_beg
    $apy0 = $tmp191;
    $apy1 = $tmp192;
    $apy2 = $tmp190;
    $arg0 = $apy0;
    $arg1 = $apy1;
    $arg2 = $apy2;
    goto __patsflab__ats2phppre_list_loop_67;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret188;
} // end-of-function


function
ats2phppre_list_ifoldleft_method($arg0, $arg1)
{
//
  $tmpret193 = NULL;
//
  __patsflab_list_ifoldleft_method:
  $tmpret193 = _ats2phppre_list_patsfun_69__closurerize($arg0, $arg1);
  return $tmpret193;
} // end-of-function


function
_ats2phppre_list_patsfun_69($env0, $env1, $arg0)
{
//
  $tmpret194 = NULL;
//
  __patsflab__ats2phppre_list_patsfun_69:
  $tmpret194 = ats2phppre_list_ifoldleft($env0, $env1, $arg0);
  return $tmpret194;
} // end-of-function


function
ats2phppre_list_foldright($arg0, $arg1, $arg2)
{
//
  $tmpret195 = NULL;
//
  __patsflab_list_foldright:
  $tmpret195 = _ats2phppre_list_aux_71($arg1, $arg0, $arg2);
  return $tmpret195;
} // end-of-function


function
_ats2phppre_list_aux_71($env0, $arg0, $arg1)
{
//
  $tmpret196 = NULL;
  $tmp197 = NULL;
  $tmp198 = NULL;
  $tmp199 = NULL;
//
  __patsflab__ats2phppre_list_aux_71:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab77:
    if(ATSCKptriscons($arg0)) goto __atstmplab80;
    __atstmplab78:
    $tmpret196 = $arg1;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab79:
    __atstmplab80:
    $tmp197 = $arg0[0];
    $tmp198 = $arg0[1];
    $tmp199 = _ats2phppre_list_aux_71($env0, $tmp198, $arg1);
    $tmpret196 = $env0[0]($env0, $tmp197, $tmp199);
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret196;
} // end-of-function


function
ats2phppre_list_foldright_method($arg0, $arg1)
{
//
  $tmpret200 = NULL;
//
  __patsflab_list_foldright_method:
  $tmpret200 = _ats2phppre_list_patsfun_73__closurerize($arg0, $arg1);
  return $tmpret200;
} // end-of-function


function
_ats2phppre_list_patsfun_73($env0, $env1, $arg0)
{
//
  $tmpret201 = NULL;
//
  __patsflab__ats2phppre_list_patsfun_73:
  $tmpret201 = ats2phppre_list_foldright($env0, $arg0, $env1);
  return $tmpret201;
} // end-of-function


function
ats2phppre_list_ifoldright($arg0, $arg1, $arg2)
{
//
  $tmpret202 = NULL;
//
  __patsflab_list_ifoldright:
  $tmpret202 = _ats2phppre_list_aux_75($arg1, 0, $arg0, $arg2);
  return $tmpret202;
} // end-of-function


function
_ats2phppre_list_aux_75($env0, $arg0, $arg1, $arg2)
{
//
  $tmpret203 = NULL;
  $tmp204 = NULL;
  $tmp205 = NULL;
  $tmp206 = NULL;
  $tmp207 = NULL;
//
  __patsflab__ats2phppre_list_aux_75:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab81:
    if(ATSCKptriscons($arg1)) goto __atstmplab84;
    __atstmplab82:
    $tmpret203 = $arg2;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab83:
    __atstmplab84:
    $tmp204 = $arg1[0];
    $tmp205 = $arg1[1];
    $tmp207 = ats2phppre_add_int1_int1($arg0, 1);
    $tmp206 = _ats2phppre_list_aux_75($env0, $tmp207, $tmp205, $arg2);
    $tmpret203 = $env0[0]($env0, $arg0, $tmp204, $tmp206);
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret203;
} // end-of-function


function
ats2phppre_list_ifoldright_method($arg0, $arg1)
{
//
  $tmpret208 = NULL;
//
  __patsflab_list_ifoldright_method:
  $tmpret208 = _ats2phppre_list_patsfun_77__closurerize($arg0, $arg1);
  return $tmpret208;
} // end-of-function


function
_ats2phppre_list_patsfun_77($env0, $env1, $arg0)
{
//
  $tmpret209 = NULL;
//
  __patsflab__ats2phppre_list_patsfun_77:
  $tmpret209 = ats2phppre_list_ifoldright($env0, $arg0, $env1);
  return $tmpret209;
} // end-of-function


function
ats2phppre_streamize_list_elt($arg0)
{
//
  $tmpret212 = NULL;
//
  __patsflab_streamize_list_elt:
  $tmpret212 = _ats2phppre_list_auxmain_81($arg0);
  return $tmpret212;
} // end-of-function


function
_ats2phppre_list_auxmain_81($arg0)
{
//
  $tmpret213 = NULL;
//
  __patsflab__ats2phppre_list_auxmain_81:
  $tmpret213 = ATSPMVllazyval(_ats2phppre_list_patsfun_82__closurerize($arg0));
  return $tmpret213;
} // end-of-function


function
_ats2phppre_list_patsfun_82($env0, $arg0)
{
//
  $tmpret214 = NULL;
  $tmp215 = NULL;
  $tmp216 = NULL;
  $tmp217 = NULL;
//
  __patsflab__ats2phppre_list_patsfun_82:
  if($arg0) {
    // ATScaseofseq_beg
    do {
      // ATSbranchseq_beg
      __atstmplab85:
      if(ATSCKptriscons($env0)) goto __atstmplab88;
      __atstmplab86:
      $tmpret214 = NULL;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      __atstmplab87:
      __atstmplab88:
      $tmp215 = $env0[0];
      $tmp216 = $env0[1];
      $tmp217 = _ats2phppre_list_auxmain_81($tmp216);
      $tmpret214 = array($tmp215, $tmp217);
      break;
      // ATSbranchseq_end
    } while(0);
    // ATScaseofseq_end
  } else {
  } // endif
  return $tmpret214;
} // end-of-function


function
ats2phppre_streamize_list_zip($arg0, $arg1)
{
//
  $tmpret218 = NULL;
//
  __patsflab_streamize_list_zip:
  $tmpret218 = _ats2phppre_list_auxmain_84($arg0, $arg1);
  return $tmpret218;
} // end-of-function


function
_ats2phppre_list_auxmain_84($arg0, $arg1)
{
//
  $tmpret219 = NULL;
//
  __patsflab__ats2phppre_list_auxmain_84:
  $tmpret219 = ATSPMVllazyval(_ats2phppre_list_patsfun_85__closurerize($arg0, $arg1));
  return $tmpret219;
} // end-of-function


function
_ats2phppre_list_patsfun_85($env0, $env1, $arg0)
{
//
  $tmpret220 = NULL;
  $tmp221 = NULL;
  $tmp222 = NULL;
  $tmp223 = NULL;
  $tmp224 = NULL;
  $tmp225 = NULL;
  $tmp226 = NULL;
//
  __patsflab__ats2phppre_list_patsfun_85:
  if($arg0) {
    // ATScaseofseq_beg
    do {
      // ATSbranchseq_beg
      __atstmplab89:
      if(ATSCKptriscons($env0)) goto __atstmplab92;
      __atstmplab90:
      $tmpret220 = NULL;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      __atstmplab91:
      __atstmplab92:
      $tmp221 = $env0[0];
      $tmp222 = $env0[1];
      // ATScaseofseq_beg
      do {
        // ATSbranchseq_beg
        __atstmplab93:
        if(ATSCKptriscons($env1)) goto __atstmplab96;
        __atstmplab94:
        $tmpret220 = NULL;
        break;
        // ATSbranchseq_end
        // ATSbranchseq_beg
        __atstmplab95:
        __atstmplab96:
        $tmp223 = $env1[0];
        $tmp224 = $env1[1];
        $tmp225 = array($tmp221, $tmp223);
        $tmp226 = _ats2phppre_list_auxmain_84($tmp222, $tmp224);
        $tmpret220 = array($tmp225, $tmp226);
        break;
        // ATSbranchseq_end
      } while(0);
      // ATScaseofseq_end
      break;
      // ATSbranchseq_end
    } while(0);
    // ATScaseofseq_end
  } else {
  } // endif
  return $tmpret220;
} // end-of-function


function
ats2phppre_streamize_list_cross($arg0, $arg1)
{
//
  $tmpret227 = NULL;
//
  __patsflab_streamize_list_cross:
  $tmpret227 = _ats2phppre_list_auxmain_89($arg0, $arg1);
  return $tmpret227;
} // end-of-function


function
_ats2phppre_list_auxone_87($arg0, $arg1)
{
//
  $tmpret228 = NULL;
//
  __patsflab__ats2phppre_list_auxone_87:
  $tmpret228 = ATSPMVllazyval(_ats2phppre_list_patsfun_88__closurerize($arg0, $arg1));
  return $tmpret228;
} // end-of-function


function
_ats2phppre_list_patsfun_88($env0, $env1, $arg0)
{
//
  $tmpret229 = NULL;
  $tmp230 = NULL;
  $tmp231 = NULL;
  $tmp232 = NULL;
  $tmp233 = NULL;
//
  __patsflab__ats2phppre_list_patsfun_88:
  if($arg0) {
    // ATScaseofseq_beg
    do {
      // ATSbranchseq_beg
      __atstmplab97:
      if(ATSCKptriscons($env1)) goto __atstmplab100;
      __atstmplab98:
      $tmpret229 = NULL;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      __atstmplab99:
      __atstmplab100:
      $tmp230 = $env1[0];
      $tmp231 = $env1[1];
      $tmp232 = array($env0, $tmp230);
      $tmp233 = _ats2phppre_list_auxone_87($env0, $tmp231);
      $tmpret229 = array($tmp232, $tmp233);
      break;
      // ATSbranchseq_end
    } while(0);
    // ATScaseofseq_end
  } else {
  } // endif
  return $tmpret229;
} // end-of-function


function
_ats2phppre_list_auxmain_89($arg0, $arg1)
{
//
  $tmpret234 = NULL;
//
  __patsflab__ats2phppre_list_auxmain_89:
  $tmpret234 = ATSPMVllazyval(_ats2phppre_list_patsfun_90__closurerize($arg0, $arg1));
  return $tmpret234;
} // end-of-function


function
_ats2phppre_list_patsfun_90($env0, $env1, $arg0)
{
//
  $tmpret235 = NULL;
  $tmp236 = NULL;
  $tmp237 = NULL;
  $tmp238 = NULL;
  $tmp239 = NULL;
  $tmp240 = NULL;
//
  __patsflab__ats2phppre_list_patsfun_90:
  if($arg0) {
    // ATScaseofseq_beg
    do {
      // ATSbranchseq_beg
      __atstmplab101:
      if(ATSCKptriscons($env0)) goto __atstmplab104;
      __atstmplab102:
      $tmpret235 = NULL;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      __atstmplab103:
      __atstmplab104:
      $tmp236 = $env0[0];
      $tmp237 = $env0[1];
      $tmp239 = _ats2phppre_list_auxone_87($tmp236, $env1);
      $tmp240 = _ats2phppre_list_auxmain_89($tmp237, $env1);
      $tmp238 = ats2phppre_stream_vt_append($tmp239, $tmp240);
      $tmpret235 = ATSPMVllazyval_eval($tmp238);
      break;
      // ATSbranchseq_end
    } while(0);
    // ATScaseofseq_end
  } else {
  } // endif
  return $tmpret235;
} // end-of-function

/* ****** ****** */

/* end-of-compilation-unit */
?>
