<?php
/*
**
** The PHP code is generated by atscc2php
** The starting compilation time is: 2016-12-19:  0h:23m
**
*/

function
ats2phppre_ref($arg0)
{
//
  $tmpret0 = NULL;
//
  __patsflab_ref:
  $tmpret0 = ats2phppre_ref_make_elt($arg0);
  return $tmpret0;
} // end-of-function


function
ats2phppre_ref_make_elt($arg0)
{
//
  $tmpret1 = NULL;
  $tmp2 = NULL;
//
  __patsflab_ref_make_elt:
  $tmp2 = PHPref_new($arg0);
  $tmpret1 = $tmp2;
  return $tmpret1;
} // end-of-function


function
ats2phppre_ref_get_elt($arg0)
{
//
  $tmpret3 = NULL;
//
  __patsflab_ref_get_elt:
  $tmpret3 = PHPref_get_elt($arg0);
  return $tmpret3;
} // end-of-function


function
ats2phppre_ref_set_elt($arg0, $arg1)
{
//
//
  __patsflab_ref_set_elt:
  PHPref_set_elt($arg0, $arg1);
  return/*_void*/;
} // end-of-function

/* ****** ****** */

/* end-of-compilation-unit */
?>
