<?php
/*
**
** The PHP code is generated by atscc2php
** The starting compilation time is: 2016-12-19:  0h:23m
**
*/

// ATSassume(ATSCC2PHP_056_slistref__slistref_type)

function
slistref_make_nil()
{
//
  $tmpret0 = NULL;
  $tmp1 = NULL;
//
  __patsflab_slistref_make_nil:
  $tmp1 = NULL;
  $tmpret0 = ats2phppre_ref($tmp1);
  return $tmpret0;
} // end-of-function


function
slistref_length($arg0)
{
//
  $tmpret2 = NULL;
  $tmp3 = NULL;
//
  __patsflab_slistref_length:
  $tmp3 = ats2phppre_ref_get_elt($arg0);
  $tmpret2 = ats2phppre_list_length($tmp3);
  return $tmpret2;
} // end-of-function


function
slistref_push($arg0, $arg1)
{
//
  $tmp5 = NULL;
  $tmp6 = NULL;
//
  __patsflab_slistref_push:
  $tmp6 = ats2phppre_ref_get_elt($arg0);
  $tmp5 = array($arg1, $tmp6);
  ats2phppre_ref_set_elt($arg0, $tmp5);
  return/*_void*/;
} // end-of-function


function
slistref_pop_opt($arg0)
{
//
  $tmpret7 = NULL;
  $tmp8 = NULL;
  $tmp9 = NULL;
  $tmp10 = NULL;
//
  __patsflab_slistref_pop_opt:
  $tmp8 = ats2phppre_ref_get_elt($arg0);
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab0:
    if(ATSCKptriscons($tmp8)) goto __atstmplab3;
    __atstmplab1:
    $tmpret7 = NULL;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab2:
    __atstmplab3:
    $tmp9 = $tmp8[0];
    $tmp10 = $tmp8[1];
    ats2phppre_ref_set_elt($arg0, $tmp10);
    $tmpret7 = array($tmp9);
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret7;
} // end-of-function


function
slistref_foldleft($arg0, $arg1, $arg2)
{
//
  $tmpret12 = NULL;
  $tmp13 = NULL;
//
  __patsflab_slistref_foldleft:
  $tmp13 = ats2phppre_ref_get_elt($arg0);
  $tmpret12 = ats2phppre_list_foldleft($tmp13, $arg1, $arg2);
  return $tmpret12;
} // end-of-function


function
slistref_foldright($arg0, $arg1, $arg2)
{
//
  $tmpret14 = NULL;
  $tmp15 = NULL;
//
  __patsflab_slistref_foldright:
  $tmp15 = ats2phppre_ref_get_elt($arg0);
  $tmpret14 = ats2phppre_list_foldright($tmp15, $arg1, $arg2);
  return $tmpret14;
} // end-of-function

/* ****** ****** */

/* end-of-compilation-unit */
?>
