<?php
/*
**
** The PHP code is generated by atscc2php
** The starting compilation time is: 2016-12-19:  0h:23m
**
*/
function
_ats2phppre_stream_vt_patsfun_7__closurerize($env0)
{
  return array(function($cenv) { return _ats2phppre_stream_vt_patsfun_7($cenv[1]); }, $env0);
}

function
_ats2phppre_stream_vt_patsfun_10__closurerize($env0, $env1)
{
  return array(function($cenv, $arg0) { return _ats2phppre_stream_vt_patsfun_10($cenv[1], $cenv[2], $arg0); }, $env0, $env1);
}

function
_ats2phppre_stream_vt_patsfun_19__closurerize($env0, $env1)
{
  return array(function($cenv, $arg0) { return _ats2phppre_stream_vt_patsfun_19($cenv[1], $cenv[2], $arg0); }, $env0, $env1);
}

function
_ats2phppre_stream_vt_patsfun_22__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_stream_vt_patsfun_22($cenv[1], $arg0); }, $env0);
}

function
_ats2phppre_stream_vt_patsfun_25__closurerize($env0, $env1)
{
  return array(function($cenv, $arg0) { return _ats2phppre_stream_vt_patsfun_25($cenv[1], $cenv[2], $arg0); }, $env0, $env1);
}

function
_ats2phppre_stream_vt_patsfun_27__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_stream_vt_patsfun_27($cenv[1], $arg0); }, $env0);
}

function
_ats2phppre_stream_vt_patsfun_30__closurerize($env0, $env1)
{
  return array(function($cenv, $arg0) { return _ats2phppre_stream_vt_patsfun_30($cenv[1], $cenv[2], $arg0); }, $env0, $env1);
}

function
_ats2phppre_stream_vt_patsfun_32__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_stream_vt_patsfun_32($cenv[1], $arg0); }, $env0);
}

function
_ats2phppre_stream_vt_patsfun_36__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_stream_vt_patsfun_36($cenv[1], $arg0); }, $env0);
}

function
_ats2phppre_stream_vt_patsfun_40__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_stream_vt_patsfun_40($cenv[1], $arg0); }, $env0);
}

function
_ats2phppre_stream_vt_patsfun_44__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_stream_vt_patsfun_44($cenv[1], $arg0); }, $env0);
}

function
_ats2phppre_stream_vt_patsfun_48__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_stream_vt_patsfun_48($cenv[1], $arg0); }, $env0);
}

function
_ats2phppre_stream_vt_patsfun_52__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2phppre_stream_vt_patsfun_52($cenv[1], $arg0); }, $env0);
}

function
_ats2phppre_stream_vt_patsfun_55__closurerize($env0, $env1)
{
  return array(function($cenv, $arg0) { return _ats2phppre_stream_vt_patsfun_55($cenv[1], $cenv[2], $arg0); }, $env0, $env1);
}


function
ats2phppre_stream_vt_free($arg0)
{
//
//
  __patsflab_stream_vt_free:
  atspre_lazy_vt_free($arg0);
  return/*_void*/;
} // end-of-function


function
ats2phppre_stream_vt2t($arg0)
{
//
  $tmpret6 = NULL;
//
  __patsflab_stream_vt2t:
  $tmpret6 = _ats2phppre_stream_vt_aux_6($arg0);
  return $tmpret6;
} // end-of-function


function
_ats2phppre_stream_vt_aux_6($arg0)
{
//
  $tmpret7 = NULL;
//
  __patsflab__ats2phppre_stream_vt_aux_6:
  $tmpret7 = ATSPMVlazyval(_ats2phppre_stream_vt_patsfun_7__closurerize($arg0));
  return $tmpret7;
} // end-of-function


function
_ats2phppre_stream_vt_patsfun_7($env0)
{
//
  $tmpret8 = NULL;
  $tmp9 = NULL;
  $tmp10 = NULL;
  $tmp11 = NULL;
  $tmp12 = NULL;
//
  __patsflab__ats2phppre_stream_vt_patsfun_7:
  $tmp9 = ATSPMVllazyval_eval($env0);
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab0:
    if(ATSCKptriscons($tmp9)) goto __atstmplab3;
    __atstmplab1:
    $tmpret8 = NULL;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab2:
    __atstmplab3:
    $tmp10 = $tmp9[0];
    $tmp11 = $tmp9[1];
    // ATSINSfreecon($tmp9);
    $tmp12 = _ats2phppre_stream_vt_aux_6($tmp11);
    $tmpret8 = array($tmp10, $tmp12);
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret8;
} // end-of-function


function
ats2phppre_stream_vt_takeLte($arg0, $arg1)
{
//
  $tmpret13 = NULL;
//
  __patsflab_stream_vt_takeLte:
  $tmpret13 = _ats2phppre_stream_vt_auxmain_9($arg0, $arg1);
  return $tmpret13;
} // end-of-function


function
_ats2phppre_stream_vt_auxmain_9($arg0, $arg1)
{
//
  $tmpret14 = NULL;
//
  __patsflab__ats2phppre_stream_vt_auxmain_9:
  $tmpret14 = ATSPMVllazyval(_ats2phppre_stream_vt_patsfun_10__closurerize($arg0, $arg1));
  return $tmpret14;
} // end-of-function


function
_ats2phppre_stream_vt_patsfun_10($env0, $env1, $arg0)
{
//
  $tmpret15 = NULL;
  $tmp16 = NULL;
  $tmp17 = NULL;
  $tmp18 = NULL;
  $tmp19 = NULL;
  $tmp20 = NULL;
  $tmp21 = NULL;
//
  __patsflab__ats2phppre_stream_vt_patsfun_10:
  if($arg0) {
    $tmp16 = ats2phppre_gt_int1_int1($env1, 0);
    if($tmp16) {
      $tmp17 = ATSPMVllazyval_eval($env0);
      // ATScaseofseq_beg
      do {
        // ATSbranchseq_beg
        __atstmplab4:
        if(ATSCKptriscons($tmp17)) goto __atstmplab7;
        __atstmplab5:
        $tmpret15 = NULL;
        break;
        // ATSbranchseq_end
        // ATSbranchseq_beg
        __atstmplab6:
        __atstmplab7:
        $tmp18 = $tmp17[0];
        $tmp19 = $tmp17[1];
        // ATSINSfreecon($tmp17);
        $tmp21 = ats2phppre_sub_int1_int1($env1, 1);
        $tmp20 = _ats2phppre_stream_vt_auxmain_9($tmp19, $tmp21);
        $tmpret15 = array($tmp18, $tmp20);
        break;
        // ATSbranchseq_end
      } while(0);
      // ATScaseofseq_end
    } else {
      atspre_lazy_vt_free($env0);
      $tmpret15 = NULL;
    } // endif
  } else {
    atspre_lazy_vt_free($env0);
  } // endif
  return $tmpret15;
} // end-of-function


function
ats2phppre_stream_vt_length($arg0)
{
//
  $tmpret24 = NULL;
//
  __patsflab_stream_vt_length:
  $tmpret24 = _ats2phppre_stream_vt_loop_12($arg0, 0);
  return $tmpret24;
} // end-of-function


function
_ats2phppre_stream_vt_loop_12($arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmpret25 = NULL;
  $tmp26 = NULL;
  $tmp28 = NULL;
  $tmp29 = NULL;
//
  __patsflab__ats2phppre_stream_vt_loop_12:
  $tmp26 = ATSPMVllazyval_eval($arg0);
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab8:
    if(ATSCKptriscons($tmp26)) goto __atstmplab11;
    __atstmplab9:
    $tmpret25 = $arg1;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab10:
    __atstmplab11:
    $tmp28 = $tmp26[1];
    // ATSINSfreecon($tmp26);
    $tmp29 = ats2phppre_add_int1_int1($arg1, 1);
    // ATStailcalseq_beg
    $apy0 = $tmp28;
    $apy1 = $tmp29;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab__ats2phppre_stream_vt_loop_12;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret25;
} // end-of-function


function
ats2phppre_stream2list_vt($arg0)
{
//
  $tmpret30 = NULL;
//
  __patsflab_stream2list_vt:
  $tmpret30 = _ats2phppre_stream_vt_aux_14($arg0);
  return $tmpret30;
} // end-of-function


function
_ats2phppre_stream_vt_aux_14($arg0)
{
//
  $tmpret31 = NULL;
  $tmp32 = NULL;
  $tmp33 = NULL;
  $tmp34 = NULL;
  $tmp35 = NULL;
//
  __patsflab__ats2phppre_stream_vt_aux_14:
  $tmp32 = ATSPMVllazyval_eval($arg0);
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab12:
    if(ATSCKptriscons($tmp32)) goto __atstmplab15;
    __atstmplab13:
    $tmpret31 = NULL;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab14:
    __atstmplab15:
    $tmp33 = $tmp32[0];
    $tmp34 = $tmp32[1];
    // ATSINSfreecon($tmp32);
    $tmp35 = _ats2phppre_stream_vt_aux_14($tmp34);
    $tmpret31 = array($tmp33, $tmp35);
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret31;
} // end-of-function


function
ats2phppre_stream2list_vt_rev($arg0)
{
//
  $tmpret36 = NULL;
  $tmp42 = NULL;
//
  __patsflab_stream2list_vt_rev:
  $tmp42 = NULL;
  $tmpret36 = _ats2phppre_stream_vt_loop_16($arg0, $tmp42);
  return $tmpret36;
} // end-of-function


function
_ats2phppre_stream_vt_loop_16($arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmpret37 = NULL;
  $tmp38 = NULL;
  $tmp39 = NULL;
  $tmp40 = NULL;
  $tmp41 = NULL;
//
  __patsflab__ats2phppre_stream_vt_loop_16:
  $tmp38 = ATSPMVllazyval_eval($arg0);
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab16:
    if(ATSCKptriscons($tmp38)) goto __atstmplab19;
    __atstmplab17:
    $tmpret37 = $arg1;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab18:
    __atstmplab19:
    $tmp39 = $tmp38[0];
    $tmp40 = $tmp38[1];
    // ATSINSfreecon($tmp38);
    $tmp41 = array($tmp39, $arg1);
    // ATStailcalseq_beg
    $apy0 = $tmp40;
    $apy1 = $tmp41;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab__ats2phppre_stream_vt_loop_16;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret37;
} // end-of-function


function
ats2phppre_stream_vt_append($arg0, $arg1)
{
//
  $tmpret43 = NULL;
//
  __patsflab_stream_vt_append:
  $tmpret43 = _ats2phppre_stream_vt_auxmain_18($arg0, $arg1);
  return $tmpret43;
} // end-of-function


function
_ats2phppre_stream_vt_auxmain_18($arg0, $arg1)
{
//
  $tmpret44 = NULL;
//
  __patsflab__ats2phppre_stream_vt_auxmain_18:
  $tmpret44 = ATSPMVllazyval(_ats2phppre_stream_vt_patsfun_19__closurerize($arg0, $arg1));
  return $tmpret44;
} // end-of-function


function
_ats2phppre_stream_vt_patsfun_19($env0, $env1, $arg0)
{
//
  $tmpret45 = NULL;
  $tmp46 = NULL;
  $tmp47 = NULL;
  $tmp48 = NULL;
  $tmp49 = NULL;
//
  __patsflab__ats2phppre_stream_vt_patsfun_19:
  if($arg0) {
    $tmp46 = ATSPMVllazyval_eval($env0);
    // ATScaseofseq_beg
    do {
      // ATSbranchseq_beg
      __atstmplab20:
      if(ATSCKptriscons($tmp46)) goto __atstmplab23;
      __atstmplab21:
      $tmpret45 = ATSPMVllazyval_eval($env1);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      __atstmplab22:
      __atstmplab23:
      $tmp47 = $tmp46[0];
      $tmp48 = $tmp46[1];
      // ATSINSfreecon($tmp46);
      $tmp49 = _ats2phppre_stream_vt_auxmain_18($tmp48, $env1);
      $tmpret45 = array($tmp47, $tmp49);
      break;
      // ATSbranchseq_end
    } while(0);
    // ATScaseofseq_end
  } else {
    atspre_lazy_vt_free($env0);
    atspre_lazy_vt_free($env1);
  } // endif
  return $tmpret45;
} // end-of-function


function
ats2phppre_stream_vt_concat($arg0)
{
//
  $tmpret52 = NULL;
//
  __patsflab_stream_vt_concat:
  $tmpret52 = _ats2phppre_stream_vt_auxmain_21($arg0);
  return $tmpret52;
} // end-of-function


function
_ats2phppre_stream_vt_auxmain_21($arg0)
{
//
  $tmpret53 = NULL;
//
  __patsflab__ats2phppre_stream_vt_auxmain_21:
  $tmpret53 = ATSPMVllazyval(_ats2phppre_stream_vt_patsfun_22__closurerize($arg0));
  return $tmpret53;
} // end-of-function


function
_ats2phppre_stream_vt_patsfun_22($env0, $arg0)
{
//
  $tmpret54 = NULL;
  $tmp55 = NULL;
  $tmp56 = NULL;
  $tmp57 = NULL;
  $tmp58 = NULL;
  $tmp59 = NULL;
//
  __patsflab__ats2phppre_stream_vt_patsfun_22:
  if($arg0) {
    $tmp55 = ATSPMVllazyval_eval($env0);
    // ATScaseofseq_beg
    do {
      // ATSbranchseq_beg
      __atstmplab24:
      if(ATSCKptriscons($tmp55)) goto __atstmplab27;
      __atstmplab25:
      $tmpret54 = NULL;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      __atstmplab26:
      __atstmplab27:
      $tmp56 = $tmp55[0];
      $tmp57 = $tmp55[1];
      // ATSINSfreecon($tmp55);
      $tmp59 = _ats2phppre_stream_vt_auxmain_21($tmp57);
      $tmp58 = ats2phppre_stream_vt_append($tmp56, $tmp59);
      $tmpret54 = ATSPMVllazyval_eval($tmp58);
      break;
      // ATSbranchseq_end
    } while(0);
    // ATScaseofseq_end
  } else {
    atspre_lazy_vt_free($env0);
  } // endif
  return $tmpret54;
} // end-of-function


function
ats2phppre_stream_vt_map_cloref($arg0, $arg1)
{
//
  $tmpret61 = NULL;
//
  __patsflab_stream_vt_map_cloref:
  $tmpret61 = _ats2phppre_stream_vt_auxmain_24($arg1, $arg0);
  return $tmpret61;
} // end-of-function


function
_ats2phppre_stream_vt_auxmain_24($env0, $arg0)
{
//
  $tmpret62 = NULL;
//
  __patsflab__ats2phppre_stream_vt_auxmain_24:
  $tmpret62 = ATSPMVllazyval(_ats2phppre_stream_vt_patsfun_25__closurerize($env0, $arg0));
  return $tmpret62;
} // end-of-function


function
_ats2phppre_stream_vt_patsfun_25($env0, $env1, $arg0)
{
//
  $tmpret63 = NULL;
  $tmp64 = NULL;
  $tmp65 = NULL;
  $tmp66 = NULL;
  $tmp67 = NULL;
  $tmp68 = NULL;
//
  __patsflab__ats2phppre_stream_vt_patsfun_25:
  if($arg0) {
    $tmp64 = ATSPMVllazyval_eval($env1);
    // ATScaseofseq_beg
    do {
      // ATSbranchseq_beg
      __atstmplab28:
      if(ATSCKptriscons($tmp64)) goto __atstmplab31;
      __atstmplab29:
      $tmpret63 = NULL;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      __atstmplab30:
      __atstmplab31:
      $tmp65 = $tmp64[0];
      $tmp66 = $tmp64[1];
      // ATSINSfreecon($tmp64);
      $tmp67 = $env0[0]($env0, $tmp65);
      $tmp68 = _ats2phppre_stream_vt_auxmain_24($env0, $tmp66);
      $tmpret63 = array($tmp67, $tmp68);
      break;
      // ATSbranchseq_end
    } while(0);
    // ATScaseofseq_end
  } else {
    atspre_lazy_vt_free($env1);
  } // endif
  return $tmpret63;
} // end-of-function


function
ats2phppre_stream_vt_map_method($arg0, $arg1)
{
//
  $tmpret70 = NULL;
//
  __patsflab_stream_vt_map_method:
  $tmpret70 = _ats2phppre_stream_vt_patsfun_27__closurerize($arg0);
  return $tmpret70;
} // end-of-function


function
_ats2phppre_stream_vt_patsfun_27($env0, $arg0)
{
//
  $tmpret71 = NULL;
//
  __patsflab__ats2phppre_stream_vt_patsfun_27:
  $tmpret71 = ats2phppre_stream_vt_map_cloref($env0, $arg0);
  return $tmpret71;
} // end-of-function


function
ats2phppre_stream_vt_filter_cloref($arg0, $arg1)
{
//
  $tmpret72 = NULL;
//
  __patsflab_stream_vt_filter_cloref:
  $tmpret72 = _ats2phppre_stream_vt_auxmain_29($arg1, $arg0);
  return $tmpret72;
} // end-of-function


function
_ats2phppre_stream_vt_auxmain_29($env0, $arg0)
{
//
  $tmpret73 = NULL;
//
  __patsflab__ats2phppre_stream_vt_auxmain_29:
  $tmpret73 = ATSPMVllazyval(_ats2phppre_stream_vt_patsfun_30__closurerize($env0, $arg0));
  return $tmpret73;
} // end-of-function


function
_ats2phppre_stream_vt_patsfun_30($env0, $env1, $arg0)
{
//
  $tmpret74 = NULL;
  $tmp75 = NULL;
  $tmp76 = NULL;
  $tmp77 = NULL;
  $tmp78 = NULL;
  $tmp79 = NULL;
  $tmp80 = NULL;
//
  __patsflab__ats2phppre_stream_vt_patsfun_30:
  if($arg0) {
    $tmp75 = ATSPMVllazyval_eval($env1);
    // ATScaseofseq_beg
    do {
      // ATSbranchseq_beg
      __atstmplab32:
      if(ATSCKptriscons($tmp75)) goto __atstmplab35;
      __atstmplab33:
      $tmpret74 = NULL;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      __atstmplab34:
      __atstmplab35:
      $tmp76 = $tmp75[0];
      $tmp77 = $tmp75[1];
      // ATSINSfreecon($tmp75);
      $tmp78 = $env0[0]($env0, $tmp76);
      if($tmp78) {
        $tmp79 = _ats2phppre_stream_vt_auxmain_29($env0, $tmp77);
        $tmpret74 = array($tmp76, $tmp79);
      } else {
        $tmp80 = _ats2phppre_stream_vt_auxmain_29($env0, $tmp77);
        $tmpret74 = ATSPMVllazyval_eval($tmp80);
      } // endif
      break;
      // ATSbranchseq_end
    } while(0);
    // ATScaseofseq_end
  } else {
    atspre_lazy_vt_free($env1);
  } // endif
  return $tmpret74;
} // end-of-function


function
ats2phppre_stream_vt_filter_method($arg0)
{
//
  $tmpret82 = NULL;
//
  __patsflab_stream_vt_filter_method:
  $tmpret82 = _ats2phppre_stream_vt_patsfun_32__closurerize($arg0);
  return $tmpret82;
} // end-of-function


function
_ats2phppre_stream_vt_patsfun_32($env0, $arg0)
{
//
  $tmpret83 = NULL;
//
  __patsflab__ats2phppre_stream_vt_patsfun_32:
  $tmpret83 = ats2phppre_stream_vt_filter_cloref($env0, $arg0);
  return $tmpret83;
} // end-of-function


function
ats2phppre_stream_vt_exists_cloref($arg0, $arg1)
{
//
  $tmpret84 = NULL;
//
  __patsflab_stream_vt_exists_cloref:
  $tmpret84 = _ats2phppre_stream_vt_loop_34($arg1, $arg0);
  return $tmpret84;
} // end-of-function


function
_ats2phppre_stream_vt_loop_34($env0, $arg0)
{
//
  $apy0 = NULL;
  $tmpret85 = NULL;
  $tmp86 = NULL;
  $tmp87 = NULL;
  $tmp88 = NULL;
  $tmp89 = NULL;
//
  __patsflab__ats2phppre_stream_vt_loop_34:
  $tmp86 = ATSPMVllazyval_eval($arg0);
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab36:
    if(ATSCKptriscons($tmp86)) goto __atstmplab39;
    __atstmplab37:
    $tmpret85 = false;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab38:
    __atstmplab39:
    $tmp87 = $tmp86[0];
    $tmp88 = $tmp86[1];
    // ATSINSfreecon($tmp86);
    $tmp89 = $env0[0]($env0, $tmp87);
    if($tmp89) {
      atspre_lazy_vt_free($tmp88);
      $tmpret85 = true;
    } else {
      // ATStailcalseq_beg
      $apy0 = $tmp88;
      $arg0 = $apy0;
      goto __patsflab__ats2phppre_stream_vt_loop_34;
      // ATStailcalseq_end
    } // endif
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret85;
} // end-of-function


function
ats2phppre_stream_vt_exists_method($arg0)
{
//
  $tmpret91 = NULL;
//
  __patsflab_stream_vt_exists_method:
  $tmpret91 = _ats2phppre_stream_vt_patsfun_36__closurerize($arg0);
  return $tmpret91;
} // end-of-function


function
_ats2phppre_stream_vt_patsfun_36($env0, $arg0)
{
//
  $tmpret92 = NULL;
//
  __patsflab__ats2phppre_stream_vt_patsfun_36:
  $tmpret92 = ats2phppre_stream_vt_exists_cloref($env0, $arg0);
  return $tmpret92;
} // end-of-function


function
ats2phppre_stream_vt_forall_cloref($arg0, $arg1)
{
//
  $tmpret93 = NULL;
//
  __patsflab_stream_vt_forall_cloref:
  $tmpret93 = _ats2phppre_stream_vt_loop_38($arg1, $arg0);
  return $tmpret93;
} // end-of-function


function
_ats2phppre_stream_vt_loop_38($env0, $arg0)
{
//
  $apy0 = NULL;
  $tmpret94 = NULL;
  $tmp95 = NULL;
  $tmp96 = NULL;
  $tmp97 = NULL;
  $tmp98 = NULL;
//
  __patsflab__ats2phppre_stream_vt_loop_38:
  $tmp95 = ATSPMVllazyval_eval($arg0);
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab40:
    if(ATSCKptriscons($tmp95)) goto __atstmplab43;
    __atstmplab41:
    $tmpret94 = true;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab42:
    __atstmplab43:
    $tmp96 = $tmp95[0];
    $tmp97 = $tmp95[1];
    // ATSINSfreecon($tmp95);
    $tmp98 = $env0[0]($env0, $tmp96);
    if($tmp98) {
      // ATStailcalseq_beg
      $apy0 = $tmp97;
      $arg0 = $apy0;
      goto __patsflab__ats2phppre_stream_vt_loop_38;
      // ATStailcalseq_end
    } else {
      atspre_lazy_vt_free($tmp97);
      $tmpret94 = false;
    } // endif
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret94;
} // end-of-function


function
ats2phppre_stream_vt_forall_method($arg0)
{
//
  $tmpret100 = NULL;
//
  __patsflab_stream_vt_forall_method:
  $tmpret100 = _ats2phppre_stream_vt_patsfun_40__closurerize($arg0);
  return $tmpret100;
} // end-of-function


function
_ats2phppre_stream_vt_patsfun_40($env0, $arg0)
{
//
  $tmpret101 = NULL;
//
  __patsflab__ats2phppre_stream_vt_patsfun_40:
  $tmpret101 = ats2phppre_stream_vt_forall_cloref($env0, $arg0);
  return $tmpret101;
} // end-of-function


function
ats2phppre_stream_vt_foreach_cloref($arg0, $arg1)
{
//
//
  __patsflab_stream_vt_foreach_cloref:
  _ats2phppre_stream_vt_loop_42($arg1, $arg0);
  return/*_void*/;
} // end-of-function


function
_ats2phppre_stream_vt_loop_42($env0, $arg0)
{
//
  $apy0 = NULL;
  $tmp104 = NULL;
  $tmp105 = NULL;
  $tmp106 = NULL;
//
  __patsflab__ats2phppre_stream_vt_loop_42:
  $tmp104 = ATSPMVllazyval_eval($arg0);
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab44:
    if(ATSCKptriscons($tmp104)) goto __atstmplab47;
    __atstmplab45:
    // ATSINSmove_void;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab46:
    __atstmplab47:
    $tmp105 = $tmp104[0];
    $tmp106 = $tmp104[1];
    // ATSINSfreecon($tmp104);
    $env0[0]($env0, $tmp105);
    // ATStailcalseq_beg
    $apy0 = $tmp106;
    $arg0 = $apy0;
    goto __patsflab__ats2phppre_stream_vt_loop_42;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
ats2phppre_stream_vt_foreach_method($arg0)
{
//
  $tmpret108 = NULL;
//
  __patsflab_stream_vt_foreach_method:
  $tmpret108 = _ats2phppre_stream_vt_patsfun_44__closurerize($arg0);
  return $tmpret108;
} // end-of-function


function
_ats2phppre_stream_vt_patsfun_44($env0, $arg0)
{
//
//
  __patsflab__ats2phppre_stream_vt_patsfun_44:
  ats2phppre_stream_vt_foreach_cloref($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ats2phppre_stream_vt_iforeach_cloref($arg0, $arg1)
{
//
//
  __patsflab_stream_vt_iforeach_cloref:
  _ats2phppre_stream_vt_loop_46($arg1, 0, $arg0);
  return/*_void*/;
} // end-of-function


function
_ats2phppre_stream_vt_loop_46($env0, $arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmp112 = NULL;
  $tmp113 = NULL;
  $tmp114 = NULL;
  $tmp116 = NULL;
//
  __patsflab__ats2phppre_stream_vt_loop_46:
  $tmp112 = ATSPMVllazyval_eval($arg1);
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab48:
    if(ATSCKptriscons($tmp112)) goto __atstmplab51;
    __atstmplab49:
    // ATSINSmove_void;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab50:
    __atstmplab51:
    $tmp113 = $tmp112[0];
    $tmp114 = $tmp112[1];
    // ATSINSfreecon($tmp112);
    $env0[0]($env0, $arg0, $tmp113);
    $tmp116 = ats2phppre_add_int1_int1($arg0, 1);
    // ATStailcalseq_beg
    $apy0 = $tmp116;
    $apy1 = $tmp114;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab__ats2phppre_stream_vt_loop_46;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
ats2phppre_stream_vt_iforeach_method($arg0)
{
//
  $tmpret117 = NULL;
//
  __patsflab_stream_vt_iforeach_method:
  $tmpret117 = _ats2phppre_stream_vt_patsfun_48__closurerize($arg0);
  return $tmpret117;
} // end-of-function


function
_ats2phppre_stream_vt_patsfun_48($env0, $arg0)
{
//
//
  __patsflab__ats2phppre_stream_vt_patsfun_48:
  ats2phppre_stream_vt_iforeach_cloref($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ats2phppre_stream_vt_rforeach_cloref($arg0, $arg1)
{
//
//
  __patsflab_stream_vt_rforeach_cloref:
  _ats2phppre_stream_vt_auxmain_50($arg1, $arg0);
  return/*_void*/;
} // end-of-function


function
_ats2phppre_stream_vt_auxmain_50($env0, $arg0)
{
//
  $tmp121 = NULL;
  $tmp122 = NULL;
  $tmp123 = NULL;
//
  __patsflab__ats2phppre_stream_vt_auxmain_50:
  $tmp121 = ATSPMVllazyval_eval($arg0);
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab52:
    if(ATSCKptriscons($tmp121)) goto __atstmplab55;
    __atstmplab53:
    // ATSINSmove_void;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab54:
    __atstmplab55:
    $tmp122 = $tmp121[0];
    $tmp123 = $tmp121[1];
    // ATSINSfreecon($tmp121);
    _ats2phppre_stream_vt_auxmain_50($env0, $tmp123);
    $env0[0]($env0, $tmp122);
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
ats2phppre_stream_vt_rforeach_method($arg0)
{
//
  $tmpret125 = NULL;
//
  __patsflab_stream_vt_rforeach_method:
  $tmpret125 = _ats2phppre_stream_vt_patsfun_52__closurerize($arg0);
  return $tmpret125;
} // end-of-function


function
_ats2phppre_stream_vt_patsfun_52($env0, $arg0)
{
//
//
  __patsflab__ats2phppre_stream_vt_patsfun_52:
  ats2phppre_stream_vt_rforeach_cloref($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ats2phppre_stream_vt_tabulate_cloref($arg0)
{
//
  $tmpret127 = NULL;
//
  __patsflab_stream_vt_tabulate_cloref:
  $tmpret127 = _ats2phppre_stream_vt_auxmain_54($arg0, 0);
  return $tmpret127;
} // end-of-function


function
_ats2phppre_stream_vt_auxmain_54($env0, $arg0)
{
//
  $tmpret128 = NULL;
//
  __patsflab__ats2phppre_stream_vt_auxmain_54:
  $tmpret128 = ATSPMVllazyval(_ats2phppre_stream_vt_patsfun_55__closurerize($env0, $arg0));
  return $tmpret128;
} // end-of-function


function
_ats2phppre_stream_vt_patsfun_55($env0, $env1, $arg0)
{
//
  $tmpret129 = NULL;
  $tmp130 = NULL;
  $tmp131 = NULL;
  $tmp132 = NULL;
//
  __patsflab__ats2phppre_stream_vt_patsfun_55:
  if($arg0) {
    $tmp130 = $env0[0]($env0, $env1);
    $tmp132 = ats2phppre_add_int1_int1($env1, 1);
    $tmp131 = _ats2phppre_stream_vt_auxmain_54($env0, $tmp132);
    $tmpret129 = array($tmp130, $tmp131);
  } else {
  } // endif
  return $tmpret129;
} // end-of-function

/* ****** ****** */

/* end-of-compilation-unit */
?>
