<?php
/*
**
** The PHP code is generated by atscc2php
** The starting compilation time is: 2016-12-19:  0h:23m
**
*/
function
_ats2jspre_stream_patsfun_6__closurerize($env0)
{
  return array(function($cenv) { return _ats2jspre_stream_patsfun_6($cenv[1]); }, $env0);
}

function
_ats2jspre_stream_patsfun_17__closurerize($env0, $env1)
{
  return array(function($cenv, $arg0) { return _ats2jspre_stream_patsfun_17($cenv[1], $cenv[2], $arg0); }, $env0, $env1);
}

function
_ats2jspre_stream_patsfun_23__closurerize($env0, $env1)
{
  return array(function($cenv) { return _ats2jspre_stream_patsfun_23($cenv[1], $cenv[2]); }, $env0, $env1);
}

function
_ats2jspre_stream_patsfun_25__closurerize($env0)
{
  return array(function($cenv) { return _ats2jspre_stream_patsfun_25($cenv[1]); }, $env0);
}

function
_ats2jspre_stream_patsfun_27__closurerize($env0, $env1)
{
  return array(function($cenv) { return _ats2jspre_stream_patsfun_27($cenv[1], $cenv[2]); }, $env0, $env1);
}

function
_ats2jspre_stream_patsfun_29__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2jspre_stream_patsfun_29($cenv[1], $arg0); }, $env0);
}

function
_ats2jspre_stream_patsfun_31__closurerize($env0, $env1)
{
  return array(function($cenv) { return _ats2jspre_stream_patsfun_31($cenv[1], $cenv[2]); }, $env0, $env1);
}

function
_ats2jspre_stream_patsfun_33__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2jspre_stream_patsfun_33($cenv[1], $arg0); }, $env0);
}

function
_ats2jspre_stream_patsfun_36__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2jspre_stream_patsfun_36($cenv[1], $arg0); }, $env0);
}

function
_ats2jspre_stream_patsfun_39__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2jspre_stream_patsfun_39($cenv[1], $arg0); }, $env0);
}

function
_ats2jspre_stream_patsfun_42__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2jspre_stream_patsfun_42($cenv[1], $arg0); }, $env0);
}

function
_ats2jspre_stream_patsfun_46__closurerize($env0)
{
  return array(function($cenv, $arg0) { return _ats2jspre_stream_patsfun_46($cenv[1], $arg0); }, $env0);
}

function
_ats2jspre_stream_patsfun_49__closurerize($env0, $env1)
{
  return array(function($cenv) { return _ats2jspre_stream_patsfun_49($cenv[1], $cenv[2]); }, $env0, $env1);
}

function
_ats2jspre_stream_patsfun_52__closurerize($env0, $env1, $env2, $env3)
{
  return array(function($cenv) { return _ats2jspre_stream_patsfun_52($cenv[1], $cenv[2], $cenv[3], $cenv[4]); }, $env0, $env1, $env2, $env3);
}

function
_ats2jspre_stream_patsfun_53__closurerize($env0, $env1)
{
  return array(function($cenv) { return _ats2jspre_stream_patsfun_53($cenv[1], $cenv[2]); }, $env0, $env1);
}

function
_ats2jspre_stream_patsfun_56__closurerize($env0)
{
  return array(function($cenv) { return _ats2jspre_stream_patsfun_56($cenv[1]); }, $env0);
}

function
_ats2jspre_stream_patsfun_58__closurerize($env0)
{
  return array(function($cenv) { return _ats2jspre_stream_patsfun_58($cenv[1]); }, $env0);
}

function
_ats2jspre_stream_patsfun_60__closurerize($env0, $env1)
{
  return array(function($cenv) { return _ats2jspre_stream_patsfun_60($cenv[1], $cenv[2]); }, $env0, $env1);
}

function
_ats2jspre_stream_patsfun_65__closurerize($env0)
{
  return array(function($cenv, $arg0, $arg1) { return _ats2jspre_stream_patsfun_65($cenv[1], $arg0, $arg1); }, $env0);
}

function
_ats2jspre_stream_patsfun_67__closurerize($env0)
{
  return array(function($cenv, $arg0, $arg1) { return _ats2jspre_stream_patsfun_67($cenv[1], $arg0, $arg1); }, $env0);
}

function
_ats2jspre_stream_patsfun_70__closurerize($env0, $env1)
{
  return array(function($cenv) { return _ats2jspre_stream_patsfun_70($cenv[1], $cenv[2]); }, $env0, $env1);
}

function
_ats2jspre_stream_patsfun_72__closurerize($env0, $env1)
{
  return array(function($cenv) { return _ats2jspre_stream_patsfun_72($cenv[1], $cenv[2]); }, $env0, $env1);
}


function
ats2phppre_stream_make_list($arg0)
{
//
  $tmpret7 = NULL;
//
  __patsflab_stream_make_list:
  $tmpret7 = ATSPMVlazyval(_ats2jspre_stream_patsfun_6__closurerize($arg0));
  return $tmpret7;
} // end-of-function


function
_ats2jspre_stream_patsfun_6($env0)
{
//
  $tmpret8 = NULL;
  $tmp9 = NULL;
  $tmp10 = NULL;
  $tmp11 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_6:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab0:
    if(ATSCKptriscons($env0)) goto __atstmplab3;
    __atstmplab1:
    $tmpret8 = NULL;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab2:
    __atstmplab3:
    $tmp9 = $env0[0];
    $tmp10 = $env0[1];
    $tmp11 = ats2phppre_stream_make_list($tmp10);
    $tmpret8 = array($tmp9, $tmp11);
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret8;
} // end-of-function


function
ats2phppre_stream_make_list0($arg0)
{
//
  $tmpret12 = NULL;
//
  __patsflab_stream_make_list0:
  $tmpret12 = ats2phppre_stream_make_list($arg0);
  return $tmpret12;
} // end-of-function


function
ats2phppre_stream_nth_opt($arg0, $arg1)
{
//
  $tmpret13 = NULL;
//
  __patsflab_stream_nth_opt:
  $tmpret13 = _ats2jspre_stream_loop_9($arg0, $arg1);
  return $tmpret13;
} // end-of-function


function
_ats2jspre_stream_loop_9($arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmpret14 = NULL;
  $tmp15 = NULL;
  $tmp16 = NULL;
  $tmp17 = NULL;
  $tmp18 = NULL;
  $tmp19 = NULL;
//
  __patsflab__ats2jspre_stream_loop_9:
  $tmp15 = ATSPMVlazyval_eval($arg0); 
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab4:
    if(ATSCKptriscons($tmp15)) goto __atstmplab7;
    __atstmplab5:
    $tmpret14 = NULL;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab6:
    __atstmplab7:
    $tmp16 = $tmp15[0];
    $tmp17 = $tmp15[1];
    $tmp18 = ats2phppre_gt_int1_int1($arg1, 0);
    if($tmp18) {
      $tmp19 = ats2phppre_pred_int1($arg1);
      // ATStailcalseq_beg
      $apy0 = $tmp17;
      $apy1 = $tmp19;
      $arg0 = $apy0;
      $arg1 = $apy1;
      goto __patsflab__ats2jspre_stream_loop_9;
      // ATStailcalseq_end
    } else {
      $tmpret14 = array($tmp16);
    } // endif
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret14;
} // end-of-function


function
ats2phppre_stream_length($arg0)
{
//
  $tmpret20 = NULL;
//
  __patsflab_stream_length:
  $tmpret20 = _ats2jspre_stream_loop_11($arg0, 0);
  return $tmpret20;
} // end-of-function


function
_ats2jspre_stream_loop_11($arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmpret21 = NULL;
  $tmp22 = NULL;
  $tmp24 = NULL;
  $tmp25 = NULL;
//
  __patsflab__ats2jspre_stream_loop_11:
  $tmp22 = ATSPMVlazyval_eval($arg0); 
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab8:
    if(ATSCKptriscons($tmp22)) goto __atstmplab11;
    __atstmplab9:
    $tmpret21 = $arg1;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab10:
    __atstmplab11:
    $tmp24 = $tmp22[1];
    $tmp25 = ats2phppre_add_int1_int1($arg1, 1);
    // ATStailcalseq_beg
    $apy0 = $tmp24;
    $apy1 = $tmp25;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab__ats2jspre_stream_loop_11;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret21;
} // end-of-function


function
ats2phppre_stream2list($arg0)
{
//
  $tmpret26 = NULL;
//
  __patsflab_stream2list:
  $tmpret26 = _ats2jspre_stream_aux_13($arg0);
  return $tmpret26;
} // end-of-function


function
_ats2jspre_stream_aux_13($arg0)
{
//
  $tmpret27 = NULL;
  $tmp28 = NULL;
  $tmp29 = NULL;
  $tmp30 = NULL;
  $tmp31 = NULL;
//
  __patsflab__ats2jspre_stream_aux_13:
  $tmp28 = ATSPMVlazyval_eval($arg0); 
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab12:
    if(ATSCKptriscons($tmp28)) goto __atstmplab15;
    __atstmplab13:
    $tmpret27 = NULL;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab14:
    __atstmplab15:
    $tmp29 = $tmp28[0];
    $tmp30 = $tmp28[1];
    $tmp31 = _ats2jspre_stream_aux_13($tmp30);
    $tmpret27 = array($tmp29, $tmp31);
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret27;
} // end-of-function


function
ats2phppre_stream2list_rev($arg0)
{
//
  $tmpret32 = NULL;
  $tmp38 = NULL;
//
  __patsflab_stream2list_rev:
  $tmp38 = NULL;
  $tmpret32 = _ats2jspre_stream_loop_15($arg0, $tmp38);
  return $tmpret32;
} // end-of-function


function
_ats2jspre_stream_loop_15($arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmpret33 = NULL;
  $tmp34 = NULL;
  $tmp35 = NULL;
  $tmp36 = NULL;
  $tmp37 = NULL;
//
  __patsflab__ats2jspre_stream_loop_15:
  $tmp34 = ATSPMVlazyval_eval($arg0); 
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab16:
    if(ATSCKptriscons($tmp34)) goto __atstmplab19;
    __atstmplab17:
    $tmpret33 = $arg1;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab18:
    __atstmplab19:
    $tmp35 = $tmp34[0];
    $tmp36 = $tmp34[1];
    $tmp37 = array($tmp35, $arg1);
    // ATStailcalseq_beg
    $apy0 = $tmp36;
    $apy1 = $tmp37;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab__ats2jspre_stream_loop_15;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret33;
} // end-of-function


function
ats2phppre_stream_takeLte($arg0, $arg1)
{
//
  $tmpret39 = NULL;
//
  __patsflab_stream_takeLte:
  $tmpret39 = ATSPMVllazyval(_ats2jspre_stream_patsfun_17__closurerize($arg0, $arg1));
  return $tmpret39;
} // end-of-function


function
_ats2jspre_stream_patsfun_17($env0, $env1, $arg0)
{
//
  $tmpret40 = NULL;
  $tmp41 = NULL;
  $tmp42 = NULL;
  $tmp43 = NULL;
  $tmp44 = NULL;
  $tmp45 = NULL;
  $tmp46 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_17:
  if($arg0) {
    $tmp41 = ats2phppre_gt_int1_int1($env1, 0);
    if($tmp41) {
      $tmp42 = ATSPMVlazyval_eval($env0); 
      // ATScaseofseq_beg
      do {
        // ATSbranchseq_beg
        __atstmplab20:
        if(ATSCKptriscons($tmp42)) goto __atstmplab23;
        __atstmplab21:
        $tmpret40 = NULL;
        break;
        // ATSbranchseq_end
        // ATSbranchseq_beg
        __atstmplab22:
        __atstmplab23:
        $tmp43 = $tmp42[0];
        $tmp44 = $tmp42[1];
        $tmp46 = ats2phppre_sub_int1_int1($env1, 1);
        $tmp45 = ats2phppre_stream_takeLte($tmp44, $tmp46);
        $tmpret40 = array($tmp43, $tmp45);
        break;
        // ATSbranchseq_end
      } while(0);
      // ATScaseofseq_end
    } else {
      $tmpret40 = NULL;
    } // endif
  } else {
  } // endif
  return $tmpret40;
} // end-of-function


function
ats2phppre_stream_take_opt($arg0, $arg1)
{
//
  $tmpret47 = NULL;
  $tmp56 = NULL;
//
  __patsflab_stream_take_opt:
  $tmp56 = NULL;
  $tmpret47 = _ats2jspre_stream_auxmain_19($arg1, $arg0, 0, $tmp56);
  return $tmpret47;
} // end-of-function


function
_ats2jspre_stream_auxmain_19($env0, $arg0, $arg1, $arg2)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $apy2 = NULL;
  $tmpret48 = NULL;
  $tmp49 = NULL;
  $tmp50 = NULL;
  $tmp51 = NULL;
  $tmp52 = NULL;
  $tmp53 = NULL;
  $tmp54 = NULL;
  $tmp55 = NULL;
//
  __patsflab__ats2jspre_stream_auxmain_19:
  $tmp49 = ats2phppre_lt_int1_int1($arg1, $env0);
  if($tmp49) {
    $tmp50 = ATSPMVlazyval_eval($arg0); 
    // ATScaseofseq_beg
    do {
      // ATSbranchseq_beg
      __atstmplab24:
      if(ATSCKptriscons($tmp50)) goto __atstmplab27;
      __atstmplab25:
      $tmpret48 = NULL;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      __atstmplab26:
      __atstmplab27:
      $tmp51 = $tmp50[0];
      $tmp52 = $tmp50[1];
      $tmp53 = ats2phppre_add_int1_int1($arg1, 1);
      $tmp54 = array($tmp51, $arg2);
      // ATStailcalseq_beg
      $apy0 = $tmp52;
      $apy1 = $tmp53;
      $apy2 = $tmp54;
      $arg0 = $apy0;
      $arg1 = $apy1;
      $arg2 = $apy2;
      goto __patsflab__ats2jspre_stream_auxmain_19;
      // ATStailcalseq_end
      break;
      // ATSbranchseq_end
    } while(0);
    // ATScaseofseq_end
  } else {
    $tmp55 = ats2phppre_list_reverse($arg2);
    $tmpret48 = array($tmp55);
  } // endif
  return $tmpret48;
} // end-of-function


function
ats2phppre_stream_drop_opt($arg0, $arg1)
{
//
  $tmpret57 = NULL;
//
  __patsflab_stream_drop_opt:
  $tmpret57 = _ats2jspre_stream_auxmain_21($arg1, $arg0, 0);
  return $tmpret57;
} // end-of-function


function
_ats2jspre_stream_auxmain_21($env0, $arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmpret58 = NULL;
  $tmp59 = NULL;
  $tmp60 = NULL;
  $tmp62 = NULL;
  $tmp63 = NULL;
//
  __patsflab__ats2jspre_stream_auxmain_21:
  $tmp59 = ats2phppre_lt_int1_int1($arg1, $env0);
  if($tmp59) {
    $tmp60 = ATSPMVlazyval_eval($arg0); 
    // ATScaseofseq_beg
    do {
      // ATSbranchseq_beg
      __atstmplab28:
      if(ATSCKptriscons($tmp60)) goto __atstmplab31;
      __atstmplab29:
      $tmpret58 = NULL;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      __atstmplab30:
      __atstmplab31:
      $tmp62 = $tmp60[1];
      $tmp63 = ats2phppre_add_int1_int1($arg1, 1);
      // ATStailcalseq_beg
      $apy0 = $tmp62;
      $apy1 = $tmp63;
      $arg0 = $apy0;
      $arg1 = $apy1;
      goto __patsflab__ats2jspre_stream_auxmain_21;
      // ATStailcalseq_end
      break;
      // ATSbranchseq_end
    } while(0);
    // ATScaseofseq_end
  } else {
    $tmpret58 = array($arg0);
  } // endif
  return $tmpret58;
} // end-of-function


function
ats2phppre_stream_append($arg0, $arg1)
{
//
  $tmpret64 = NULL;
//
  __patsflab_stream_append:
  $tmpret64 = ATSPMVlazyval(_ats2jspre_stream_patsfun_23__closurerize($arg0, $arg1));
  return $tmpret64;
} // end-of-function


function
_ats2jspre_stream_patsfun_23($env0, $env1)
{
//
  $tmpret65 = NULL;
  $tmp66 = NULL;
  $tmp67 = NULL;
  $tmp68 = NULL;
  $tmp69 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_23:
  $tmp66 = ATSPMVlazyval_eval($env0); 
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab32:
    if(ATSCKptriscons($tmp66)) goto __atstmplab35;
    __atstmplab33:
    $tmpret65 = ATSPMVlazyval_eval($env1); 
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab34:
    __atstmplab35:
    $tmp67 = $tmp66[0];
    $tmp68 = $tmp66[1];
    $tmp69 = ats2phppre_stream_append($tmp68, $env1);
    $tmpret65 = array($tmp67, $tmp69);
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret65;
} // end-of-function


function
ats2phppre_stream_concat($arg0)
{
//
  $tmpret70 = NULL;
//
  __patsflab_stream_concat:
  $tmpret70 = ATSPMVlazyval(_ats2jspre_stream_patsfun_25__closurerize($arg0));
  return $tmpret70;
} // end-of-function


function
_ats2jspre_stream_patsfun_25($env0)
{
//
  $tmpret71 = NULL;
  $tmp72 = NULL;
  $tmp73 = NULL;
  $tmp74 = NULL;
  $tmp75 = NULL;
  $tmp76 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_25:
  $tmp72 = ATSPMVlazyval_eval($env0); 
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab36:
    if(ATSCKptriscons($tmp72)) goto __atstmplab39;
    __atstmplab37:
    $tmpret71 = NULL;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab38:
    __atstmplab39:
    $tmp73 = $tmp72[0];
    $tmp74 = $tmp72[1];
    $tmp76 = ats2phppre_stream_concat($tmp74);
    $tmp75 = ats2phppre_stream_append($tmp73, $tmp76);
    $tmpret71 = ATSPMVlazyval_eval($tmp75); 
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret71;
} // end-of-function


function
ats2phppre_stream_map_cloref($arg0, $arg1)
{
//
  $tmpret77 = NULL;
//
  __patsflab_stream_map_cloref:
  $tmpret77 = ATSPMVlazyval(_ats2jspre_stream_patsfun_27__closurerize($arg0, $arg1));
  return $tmpret77;
} // end-of-function


function
_ats2jspre_stream_patsfun_27($env0, $env1)
{
//
  $tmpret78 = NULL;
  $tmp79 = NULL;
  $tmp80 = NULL;
  $tmp81 = NULL;
  $tmp82 = NULL;
  $tmp83 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_27:
  $tmp79 = ATSPMVlazyval_eval($env0); 
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab40:
    if(ATSCKptriscons($tmp79)) goto __atstmplab43;
    __atstmplab41:
    $tmpret78 = NULL;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab42:
    __atstmplab43:
    $tmp80 = $tmp79[0];
    $tmp81 = $tmp79[1];
    $tmp82 = $env1[0]($env1, $tmp80);
    $tmp83 = ats2phppre_stream_map_cloref($tmp81, $env1);
    $tmpret78 = array($tmp82, $tmp83);
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret78;
} // end-of-function


function
ats2phppre_stream_map_method($arg0, $arg1)
{
//
  $tmpret84 = NULL;
//
  __patsflab_stream_map_method:
  $tmpret84 = _ats2jspre_stream_patsfun_29__closurerize($arg0);
  return $tmpret84;
} // end-of-function


function
_ats2jspre_stream_patsfun_29($env0, $arg0)
{
//
  $tmpret85 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_29:
  $tmpret85 = ats2phppre_stream_map_cloref($env0, $arg0);
  return $tmpret85;
} // end-of-function


function
ats2phppre_stream_filter_cloref($arg0, $arg1)
{
//
  $tmpret86 = NULL;
//
  __patsflab_stream_filter_cloref:
  $tmpret86 = ATSPMVlazyval(_ats2jspre_stream_patsfun_31__closurerize($arg0, $arg1));
  return $tmpret86;
} // end-of-function


function
_ats2jspre_stream_patsfun_31($env0, $env1)
{
//
  $tmpret87 = NULL;
  $tmp88 = NULL;
  $tmp89 = NULL;
  $tmp90 = NULL;
  $tmp91 = NULL;
  $tmp92 = NULL;
  $tmp93 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_31:
  $tmp88 = ATSPMVlazyval_eval($env0); 
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab44:
    if(ATSCKptriscons($tmp88)) goto __atstmplab47;
    __atstmplab45:
    $tmpret87 = NULL;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab46:
    __atstmplab47:
    $tmp89 = $tmp88[0];
    $tmp90 = $tmp88[1];
    $tmp91 = $env1[0]($env1, $tmp89);
    if($tmp91) {
      $tmp92 = ats2phppre_stream_filter_cloref($tmp90, $env1);
      $tmpret87 = array($tmp89, $tmp92);
    } else {
      $tmp93 = ats2phppre_stream_filter_cloref($tmp90, $env1);
      $tmpret87 = ATSPMVlazyval_eval($tmp93); 
    } // endif
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret87;
} // end-of-function


function
ats2phppre_stream_filter_method($arg0)
{
//
  $tmpret94 = NULL;
//
  __patsflab_stream_filter_method:
  $tmpret94 = _ats2jspre_stream_patsfun_33__closurerize($arg0);
  return $tmpret94;
} // end-of-function


function
_ats2jspre_stream_patsfun_33($env0, $arg0)
{
//
  $tmpret95 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_33:
  $tmpret95 = ats2phppre_stream_filter_cloref($env0, $arg0);
  return $tmpret95;
} // end-of-function


function
ats2phppre_stream_forall_cloref($arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmpret96 = NULL;
  $tmp97 = NULL;
  $tmp98 = NULL;
  $tmp99 = NULL;
  $tmp100 = NULL;
//
  __patsflab_stream_forall_cloref:
  $tmp97 = ATSPMVlazyval_eval($arg0); 
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab48:
    if(ATSCKptriscons($tmp97)) goto __atstmplab51;
    __atstmplab49:
    $tmpret96 = true;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab50:
    __atstmplab51:
    $tmp98 = $tmp97[0];
    $tmp99 = $tmp97[1];
    $tmp100 = $arg1[0]($arg1, $tmp98);
    if($tmp100) {
      // ATStailcalseq_beg
      $apy0 = $tmp99;
      $apy1 = $arg1;
      $arg0 = $apy0;
      $arg1 = $apy1;
      goto __patsflab_stream_forall_cloref;
      // ATStailcalseq_end
    } else {
      $tmpret96 = false;
    } // endif
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret96;
} // end-of-function


function
ats2phppre_stream_forall_method($arg0)
{
//
  $tmpret101 = NULL;
//
  __patsflab_stream_forall_method:
  $tmpret101 = _ats2jspre_stream_patsfun_36__closurerize($arg0);
  return $tmpret101;
} // end-of-function


function
_ats2jspre_stream_patsfun_36($env0, $arg0)
{
//
  $tmpret102 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_36:
  $tmpret102 = ats2phppre_stream_forall_cloref($env0, $arg0);
  return $tmpret102;
} // end-of-function


function
ats2phppre_stream_exists_cloref($arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmpret103 = NULL;
  $tmp104 = NULL;
  $tmp105 = NULL;
  $tmp106 = NULL;
  $tmp107 = NULL;
//
  __patsflab_stream_exists_cloref:
  $tmp104 = ATSPMVlazyval_eval($arg0); 
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab52:
    if(ATSCKptriscons($tmp104)) goto __atstmplab55;
    __atstmplab53:
    $tmpret103 = false;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab54:
    __atstmplab55:
    $tmp105 = $tmp104[0];
    $tmp106 = $tmp104[1];
    $tmp107 = $arg1[0]($arg1, $tmp105);
    if($tmp107) {
      $tmpret103 = true;
    } else {
      // ATStailcalseq_beg
      $apy0 = $tmp106;
      $apy1 = $arg1;
      $arg0 = $apy0;
      $arg1 = $apy1;
      goto __patsflab_stream_exists_cloref;
      // ATStailcalseq_end
    } // endif
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret103;
} // end-of-function


function
ats2phppre_stream_exists_method($arg0)
{
//
  $tmpret108 = NULL;
//
  __patsflab_stream_exists_method:
  $tmpret108 = _ats2jspre_stream_patsfun_39__closurerize($arg0);
  return $tmpret108;
} // end-of-function


function
_ats2jspre_stream_patsfun_39($env0, $arg0)
{
//
  $tmpret109 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_39:
  $tmpret109 = ats2phppre_stream_exists_cloref($env0, $arg0);
  return $tmpret109;
} // end-of-function


function
ats2phppre_stream_foreach_cloref($arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmp111 = NULL;
  $tmp112 = NULL;
  $tmp113 = NULL;
//
  __patsflab_stream_foreach_cloref:
  $tmp111 = ATSPMVlazyval_eval($arg0); 
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab56:
    if(ATSCKptriscons($tmp111)) goto __atstmplab59;
    __atstmplab57:
    // ATSINSmove_void;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab58:
    __atstmplab59:
    $tmp112 = $tmp111[0];
    $tmp113 = $tmp111[1];
    $arg1[0]($arg1, $tmp112);
    // ATStailcalseq_beg
    $apy0 = $tmp113;
    $apy1 = $arg1;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab_stream_foreach_cloref;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
ats2phppre_stream_foreach_method($arg0)
{
//
  $tmpret115 = NULL;
//
  __patsflab_stream_foreach_method:
  $tmpret115 = _ats2jspre_stream_patsfun_42__closurerize($arg0);
  return $tmpret115;
} // end-of-function


function
_ats2jspre_stream_patsfun_42($env0, $arg0)
{
//
//
  __patsflab__ats2jspre_stream_patsfun_42:
  ats2phppre_stream_foreach_cloref($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ats2phppre_stream_iforeach_cloref($arg0, $arg1)
{
//
//
  __patsflab_stream_iforeach_cloref:
  _ats2jspre_stream_loop_44($arg1, 0, $arg0);
  return/*_void*/;
} // end-of-function


function
_ats2jspre_stream_loop_44($env0, $arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmp119 = NULL;
  $tmp120 = NULL;
  $tmp121 = NULL;
  $tmp123 = NULL;
//
  __patsflab__ats2jspre_stream_loop_44:
  $tmp119 = ATSPMVlazyval_eval($arg1); 
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab60:
    if(ATSCKptriscons($tmp119)) goto __atstmplab63;
    __atstmplab61:
    // ATSINSmove_void;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab62:
    __atstmplab63:
    $tmp120 = $tmp119[0];
    $tmp121 = $tmp119[1];
    $env0[0]($env0, $arg0, $tmp120);
    $tmp123 = ats2phppre_add_int1_int1($arg0, 1);
    // ATStailcalseq_beg
    $apy0 = $tmp123;
    $apy1 = $tmp121;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab__ats2jspre_stream_loop_44;
    // ATStailcalseq_end
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
ats2phppre_stream_iforeach_method($arg0)
{
//
  $tmpret124 = NULL;
//
  __patsflab_stream_iforeach_method:
  $tmpret124 = _ats2jspre_stream_patsfun_46__closurerize($arg0);
  return $tmpret124;
} // end-of-function


function
_ats2jspre_stream_patsfun_46($env0, $arg0)
{
//
//
  __patsflab__ats2jspre_stream_patsfun_46:
  ats2phppre_stream_iforeach_cloref($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ats2phppre_stream_tabulate_cloref($arg0)
{
//
  $tmpret126 = NULL;
//
  __patsflab_stream_tabulate_cloref:
  $tmpret126 = _ats2jspre_stream_auxmain_48($arg0, 0);
  return $tmpret126;
} // end-of-function


function
_ats2jspre_stream_auxmain_48($env0, $arg0)
{
//
  $tmpret127 = NULL;
//
  __patsflab__ats2jspre_stream_auxmain_48:
  $tmpret127 = ATSPMVlazyval(_ats2jspre_stream_patsfun_49__closurerize($env0, $arg0));
  return $tmpret127;
} // end-of-function


function
_ats2jspre_stream_patsfun_49($env0, $env1)
{
//
  $tmpret128 = NULL;
  $tmp129 = NULL;
  $tmp130 = NULL;
  $tmp131 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_49:
  $tmp129 = $env0[0]($env0, $env1);
  $tmp131 = ats2phppre_add_int1_int1($env1, 1);
  $tmp130 = _ats2jspre_stream_auxmain_48($env0, $tmp131);
  $tmpret128 = array($tmp129, $tmp130);
  return $tmpret128;
} // end-of-function


function
ats2phppre_cross_stream_list($arg0, $arg1)
{
//
  $tmpret132 = NULL;
//
  __patsflab_cross_stream_list:
  $tmpret132 = ATSPMVlazyval(_ats2jspre_stream_patsfun_53__closurerize($arg0, $arg1));
  return $tmpret132;
} // end-of-function


function
_ats2jspre_stream_auxmain_51($arg0, $arg1, $arg2, $arg3)
{
//
  $tmpret133 = NULL;
//
  __patsflab__ats2jspre_stream_auxmain_51:
  $tmpret133 = ATSPMVlazyval(_ats2jspre_stream_patsfun_52__closurerize($arg0, $arg1, $arg2, $arg3));
  return $tmpret133;
} // end-of-function


function
_ats2jspre_stream_patsfun_52($env0, $env1, $env2, $env3)
{
//
  $tmpret134 = NULL;
  $tmp135 = NULL;
  $tmp136 = NULL;
  $tmp137 = NULL;
  $tmp138 = NULL;
  $tmp139 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_52:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab64:
    if(ATSCKptriscons($env3)) goto __atstmplab67;
    __atstmplab65:
    $tmp137 = ats2phppre_cross_stream_list($env1, $env2);
    $tmpret134 = ATSPMVlazyval_eval($tmp137); 
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab66:
    __atstmplab67:
    $tmp135 = $env3[0];
    $tmp136 = $env3[1];
    $tmp138 = array($env0, $tmp135);
    $tmp139 = _ats2jspre_stream_auxmain_51($env0, $env1, $env2, $tmp136);
    $tmpret134 = array($tmp138, $tmp139);
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret134;
} // end-of-function


function
_ats2jspre_stream_patsfun_53($env0, $env1)
{
//
  $tmpret140 = NULL;
  $tmp141 = NULL;
  $tmp142 = NULL;
  $tmp143 = NULL;
  $tmp144 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_53:
  $tmp141 = ATSPMVlazyval_eval($env0); 
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab68:
    if(ATSCKptriscons($tmp141)) goto __atstmplab71;
    __atstmplab69:
    $tmpret140 = NULL;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab70:
    if(ATSCKptrisnull($tmp141)) ATSINScaseof_fail("/home/hwxi/Research/ATS-Postiats-contrib/contrib/libatscc/DATS/stream.dats: 6907(line=451, offs=1) -- 6999(line=453, offs=50)");
    __atstmplab71:
    $tmp142 = $tmp141[0];
    $tmp143 = $tmp141[1];
    $tmp144 = _ats2jspre_stream_auxmain_51($tmp142, $tmp143, $env1, $env1);
    $tmpret140 = ATSPMVlazyval_eval($tmp144); 
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret140;
} // end-of-function


function
ats2phppre_cross_stream_list0($arg0, $arg1)
{
//
  $tmpret145 = NULL;
//
  __patsflab_cross_stream_list0:
  $tmpret145 = ats2phppre_cross_stream_list($arg0, $arg1);
  return $tmpret145;
} // end-of-function


function
ats2phppre_stream2cloref_exn($arg0)
{
//
  $tmpret146 = NULL;
  $tmp147 = NULL;
//
  __patsflab_stream2cloref_exn:
  $tmp147 = ats2phppre_ref($arg0);
  $tmpret146 = _ats2jspre_stream_patsfun_56__closurerize($tmp147);
  return $tmpret146;
} // end-of-function


function
_ats2jspre_stream_patsfun_56($env0)
{
//
  $tmpret148 = NULL;
  $tmp149 = NULL;
  $tmp150 = NULL;
  $tmp151 = NULL;
  $tmp152 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_56:
  $tmp149 = ats2phppre_ref_get_elt($env0);
  $tmp150 = ATSPMVlazyval_eval($tmp149); 
  if(ATSCKptrisnull($tmp150)) ATSINScaseof_fail("/home/hwxi/Research/ATS-Postiats-contrib/contrib/libatscc/DATS/stream.dats: 7300(line=479, offs=5) -- 7324(line=479, offs=29)");
  $tmp151 = $tmp150[0];
  $tmp152 = $tmp150[1];
  ats2phppre_ref_set_elt($env0, $tmp152);
  $tmpret148 = $tmp151;
  return $tmpret148;
} // end-of-function


function
ats2phppre_stream2cloref_opt($arg0)
{
//
  $tmpret154 = NULL;
  $tmp155 = NULL;
//
  __patsflab_stream2cloref_opt:
  $tmp155 = ats2phppre_ref($arg0);
  $tmpret154 = _ats2jspre_stream_patsfun_58__closurerize($tmp155);
  return $tmpret154;
} // end-of-function


function
_ats2jspre_stream_patsfun_58($env0)
{
//
  $tmpret156 = NULL;
  $tmp157 = NULL;
  $tmp158 = NULL;
  $tmp159 = NULL;
  $tmp160 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_58:
  $tmp157 = ats2phppre_ref_get_elt($env0);
  $tmp158 = ATSPMVlazyval_eval($tmp157); 
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab72:
    if(ATSCKptriscons($tmp158)) goto __atstmplab75;
    __atstmplab73:
    $tmpret156 = NULL;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab74:
    __atstmplab75:
    $tmp159 = $tmp158[0];
    $tmp160 = $tmp158[1];
    ats2phppre_ref_set_elt($env0, $tmp160);
    $tmpret156 = array($tmp159);
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret156;
} // end-of-function


function
ats2phppre_stream2cloref_last($arg0, $arg1)
{
//
  $tmpret162 = NULL;
  $tmp163 = NULL;
  $tmp164 = NULL;
//
  __patsflab_stream2cloref_last:
  $tmp163 = ats2phppre_ref($arg0);
  $tmp164 = ats2phppre_ref($arg1);
  $tmpret162 = _ats2jspre_stream_patsfun_60__closurerize($tmp163, $tmp164);
  return $tmpret162;
} // end-of-function


function
_ats2jspre_stream_patsfun_60($env0, $env1)
{
//
  $tmpret165 = NULL;
  $tmp166 = NULL;
  $tmp167 = NULL;
  $tmp168 = NULL;
  $tmp169 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_60:
  $tmp166 = ats2phppre_ref_get_elt($env0);
  $tmp167 = ATSPMVlazyval_eval($tmp166); 
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab76:
    if(ATSCKptriscons($tmp167)) goto __atstmplab79;
    __atstmplab77:
    $tmpret165 = ats2phppre_ref_get_elt($env1);
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab78:
    __atstmplab79:
    $tmp168 = $tmp167[0];
    $tmp169 = $tmp167[1];
    ats2phppre_ref_set_elt($env0, $tmp169);
    ats2phppre_ref_set_elt($env1, $tmp168);
    $tmpret165 = $tmp168;
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret165;
} // end-of-function


function
ats2phppre_stream_take_while_cloref($arg0, $arg1)
{
//
  $tmpret172 = NULL;
  $tmp173 = NULL;
  $tmp174 = NULL;
  $tmp175 = NULL;
  $tmp176 = NULL;
//
  __patsflab_stream_take_while_cloref:
  $tmp173 = ats2phppre_stream_rtake_while_cloref($arg0, $arg1);
  $tmp174 = $tmp173[0];
  $tmp175 = $tmp173[1];
  $tmp176 = ats2phppre_list_reverse($tmp175);
  $tmpret172 = array($tmp174, $tmp176);
  return $tmpret172;
} // end-of-function


function
ats2phppre_stream_rtake_while_cloref($arg0, $arg1)
{
//
  $tmpret177 = NULL;
  $tmp185 = NULL;
//
  __patsflab_stream_rtake_while_cloref:
  $tmp185 = NULL;
  $tmpret177 = _ats2jspre_stream_loop_63($arg1, $arg0, 0, $tmp185);
  return $tmpret177;
} // end-of-function


function
_ats2jspre_stream_loop_63($env0, $arg0, $arg1, $arg2)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $apy2 = NULL;
  $tmpret178 = NULL;
  $tmp179 = NULL;
  $tmp180 = NULL;
  $tmp181 = NULL;
  $tmp182 = NULL;
  $tmp183 = NULL;
  $tmp184 = NULL;
//
  __patsflab__ats2jspre_stream_loop_63:
  $tmp179 = ATSPMVlazyval_eval($arg0); 
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab80:
    if(ATSCKptriscons($tmp179)) goto __atstmplab83;
    __atstmplab81:
    $tmpret178 = array($arg0, $arg2);
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab82:
    __atstmplab83:
    $tmp180 = $tmp179[0];
    $tmp181 = $tmp179[1];
    $tmp182 = $env0[0]($env0, $arg1, $tmp180);
    if($tmp182) {
      $tmp183 = ats2phppre_add_int1_int1($arg1, 1);
      $tmp184 = array($tmp180, $arg2);
      // ATStailcalseq_beg
      $apy0 = $tmp181;
      $apy1 = $tmp183;
      $apy2 = $tmp184;
      $arg0 = $apy0;
      $arg1 = $apy1;
      $arg2 = $apy2;
      goto __patsflab__ats2jspre_stream_loop_63;
      // ATStailcalseq_end
    } else {
      $tmpret178 = array($arg0, $arg2);
    } // endif
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret178;
} // end-of-function


function
ats2phppre_stream_take_until_cloref($arg0, $arg1)
{
//
  $tmpret186 = NULL;
//
  __patsflab_stream_take_until_cloref:
  $tmpret186 = ats2phppre_stream_take_while_cloref($arg0, _ats2jspre_stream_patsfun_65__closurerize($arg1));
  return $tmpret186;
} // end-of-function


function
_ats2jspre_stream_patsfun_65($env0, $arg0, $arg1)
{
//
  $tmpret187 = NULL;
  $tmp188 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_65:
  $tmp188 = $env0[0]($env0, $arg0, $arg1);
  $tmpret187 = atspre_neg_bool0($tmp188);
  return $tmpret187;
} // end-of-function


function
ats2phppre_stream_rtake_until_cloref($arg0, $arg1)
{
//
  $tmpret189 = NULL;
//
  __patsflab_stream_rtake_until_cloref:
  $tmpret189 = ats2phppre_stream_rtake_while_cloref($arg0, _ats2jspre_stream_patsfun_67__closurerize($arg1));
  return $tmpret189;
} // end-of-function


function
_ats2jspre_stream_patsfun_67($env0, $arg0, $arg1)
{
//
  $tmpret190 = NULL;
  $tmp191 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_67:
  $tmp191 = $env0[0]($env0, $arg0, $arg1);
  $tmpret190 = atspre_neg_bool0($tmp191);
  return $tmpret190;
} // end-of-function


function
ats2phppre_stream_list_xprod2($arg0, $arg1)
{
//
  $tmpret192 = NULL;
//
  __patsflab_stream_list_xprod2:
  $tmpret192 = _ats2jspre_stream_auxlst_71($arg0, $arg1);
  return $tmpret192;
} // end-of-function


function
_ats2jspre_stream_aux_69($arg0, $arg1)
{
//
  $tmpret193 = NULL;
//
  __patsflab__ats2jspre_stream_aux_69:
  $tmpret193 = ATSPMVlazyval(_ats2jspre_stream_patsfun_70__closurerize($arg0, $arg1));
  return $tmpret193;
} // end-of-function


function
_ats2jspre_stream_patsfun_70($env0, $env1)
{
//
  $tmpret194 = NULL;
  $tmp195 = NULL;
  $tmp196 = NULL;
  $tmp197 = NULL;
  $tmp198 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_70:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab84:
    if(ATSCKptriscons($env1)) goto __atstmplab87;
    __atstmplab85:
    $tmpret194 = NULL;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab86:
    __atstmplab87:
    $tmp195 = $env1[0];
    $tmp196 = $env1[1];
    $tmp197 = array($env0, $tmp195);
    $tmp198 = _ats2jspre_stream_aux_69($env0, $tmp196);
    $tmpret194 = array($tmp197, $tmp198);
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret194;
} // end-of-function


function
_ats2jspre_stream_auxlst_71($arg0, $arg1)
{
//
  $tmpret199 = NULL;
//
  __patsflab__ats2jspre_stream_auxlst_71:
  $tmpret199 = ATSPMVlazyval(_ats2jspre_stream_patsfun_72__closurerize($arg0, $arg1));
  return $tmpret199;
} // end-of-function


function
_ats2jspre_stream_patsfun_72($env0, $env1)
{
//
  $tmpret200 = NULL;
  $tmp201 = NULL;
  $tmp202 = NULL;
  $tmp203 = NULL;
  $tmp204 = NULL;
  $tmp205 = NULL;
//
  __patsflab__ats2jspre_stream_patsfun_72:
  // ATScaseofseq_beg
  do {
    // ATSbranchseq_beg
    __atstmplab88:
    if(ATSCKptriscons($env0)) goto __atstmplab91;
    __atstmplab89:
    $tmpret200 = NULL;
    break;
    // ATSbranchseq_end
    // ATSbranchseq_beg
    __atstmplab90:
    __atstmplab91:
    $tmp201 = $env0[0];
    $tmp202 = $env0[1];
    $tmp204 = _ats2jspre_stream_aux_69($tmp201, $env1);
    $tmp205 = _ats2jspre_stream_auxlst_71($tmp202, $env1);
    $tmp203 = ats2phppre_stream_append($tmp204, $tmp205);
    $tmpret200 = ATSPMVlazyval_eval($tmp203); 
    break;
    // ATSbranchseq_end
  } while(0);
  // ATScaseofseq_end
  return $tmpret200;
} // end-of-function

/* ****** ****** */

/* end-of-compilation-unit */
?>
