/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2016-12-27: 17h:12m
**
*/

/* ATSextcode_beg() */
//
function
emcc_string(inp)
{
//
var
out = Module._malloc(inp.length+1);
//
Module.writeStringToMemory(inp, out); return out;
//
} // end of [emcc_string]
//
function
emcc_stringify(ptr) { return Pointer_stringify(ptr); }
//
/* ATSextcode_end() */

/* ATSextcode_beg() */
//
function
theExample_dats_c_get_value()
{
  return document.getElementById("theExample_dats_c").value;
}
function
theExample_dats_js_set_value(code)
{
  return document.getElementById("theExample_dats_js").value = code;
}
//
function
theExample_atscc2js_optstr_get_value()
{
  return document.getElementById("theExample_atscc2js_optstr").value;
}
//
/* ATSextcode_end() */

function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057_CBOOT_057_JS_057_TEST_057_test_libatscc2js_056_dats__comarg_strlit(arg0)
{
//
// knd = 0
  var tmpret0
  var tmp1
  var tmplab, tmplab_js
//
  // __patsflab_comarg_strlit
  tmp1 = emcc_string(arg0);
  tmpret0 = _libatscc2js_comarg_strlit(tmp1);
  return tmpret0;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057_CBOOT_057_JS_057_TEST_057_test_libatscc2js_056_dats__comarg_strinp(arg0)
{
//
// knd = 0
  var tmpret2
  var tmp3
  var tmplab, tmplab_js
//
  // __patsflab_comarg_strinp
  tmp3 = emcc_string(arg0);
  tmpret2 = _libatscc2js_comarg_strinp(tmp3);
  return tmpret2;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057_CBOOT_057_JS_057_TEST_057_test_libatscc2js_056_dats__comarg_prefil(arg0)
{
//
// knd = 0
  var tmpret4
  var tmp5
  var tmplab, tmplab_js
//
  // __patsflab_comarg_prefil
  tmp5 = emcc_string(arg0);
  tmpret4 = _libatscc2js_comarg_prefil(tmp5);
  return tmpret4;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057_CBOOT_057_JS_057_TEST_057_test_libatscc2js_056_dats__comarg_postfil(arg0)
{
//
// knd = 0
  var tmpret6
  var tmp7
  var tmplab, tmplab_js
//
  // __patsflab_comarg_postfil
  tmp7 = emcc_string(arg0);
  tmpret6 = _libatscc2js_comarg_postfil(tmp7);
  return tmpret6;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057_CBOOT_057_JS_057_TEST_057_test_libatscc2js_056_dats__theExample_atscc2js_getarg()
{
//
// knd = 0
  var tmpret8
  var tmp9
  var tmp10
  var tmp11
  var tmp12
  var tmp13
  var tmp14
  var tmp21
  var tmplab, tmplab_js
//
  // __patsflab_theExample_atscc2js_getarg
  tmp9 = theExample_dats_c_get_value();
  tmp10 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057_CBOOT_057_JS_057_TEST_057_test_libatscc2js_056_dats__comarg_strinp(tmp9);
  tmp11 = _libatscc2js_comarglst_nil();
  tmp12 = _libatscc2js_comarglst_cons(tmp10, tmp11);
  tmp13 = theExample_atscc2js_optstr_get_value();
  tmp14 = tmp13.split(" ");
  tmp21 = ats2jspre_JSarray_length(tmp14);
  tmpret8 = aux_5(tmp14, tmp21, tmp12);
  return tmpret8;
} // end-of-function


function
aux_5(env0, arg0, arg1)
{
//
// knd = 1
  var apy0
  var apy1
  var tmpret15
  var tmp16
  var tmp17
  var tmp18
  var tmp19
  var tmp20
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_aux_5
    tmp16 = ats2jspre_gt_int0_int0(arg0, 0);
    if(tmp16) {
      tmp17 = ats2jspre_sub_int0_int0(arg0, 1);
      tmp19 = ats2jspre_JSarray_get_at(env0, tmp17);
      tmp18 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057_CBOOT_057_JS_057_TEST_057_test_libatscc2js_056_dats__comarg_strlit(tmp19);
      tmp20 = _libatscc2js_comarglst_cons(tmp18, arg1);
      // ATStailcalseq_beg
      apy0 = tmp17;
      apy1 = tmp20;
      arg0 = apy0;
      arg1 = apy1;
      funlab_js = 1; // __patsflab_aux_5
      // ATStailcalseq_end
    } else {
      tmpret15 = arg1;
    } // endif
    if (funlab_js > 0) continue; else return tmpret15;
  } // endwhile-fun
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057_CBOOT_057_JS_057_TEST_057_test_libatscc2js_056_dats__theExample_atscc2js_arglst(arg0)
{
//
// knd = 0
  var tmpret22
  var tmp24
  var tmp25
  var tmp26
  var tmp28
  var tmp30
  var tmp32
  var tmp34
  var tmp36
  var tmplab, tmplab_js
//
  // __patsflab_theExample_atscc2js_arglst
  _libatscc2js_dynload();
  tmp24 = _libatscc2js_atscc2js_main0_arglst(arg0);
  tmp25 = libatscc2js_stdout_store_join();
  tmp26 = libatscc2js_stderr_store_join();
  tmp28 = ats2jspre_eq_int0_int0(tmp24, 0);
  if(tmp28) {
    theExample_dats_js_set_value(tmp25);
  } else {
    // ATSINSmove_void
  } // endif
  tmp30 = ats2jspre_gt_int0_int0(tmp24, 0);
  if(tmp30) {
    theExample_dats_js_set_value(tmp26);
  } else {
    // ATSINSmove_void
  } // endif
  tmp32 = ats2jspre_eq_int0_int0(tmp24, 0);
  if(tmp32) {
    ats2jspre_alert("Atscc2js finished normally!");
  } else {
    // ATSINSmove_void
  } // endif
  tmp34 = ats2jspre_gte_int0_int0(tmp24, 1);
  if(tmp34) {
    ats2jspre_alert("Atscc2js encountered an error!");
  } else {
    // ATSINSmove_void
  } // endif
  tmp36 = ats2jspre_gte_int0_int0(tmp24, 2);
  if(tmp36) {
    ats2jspre_alert("Atscc2js encountered some errors!");
  } else {
    // ATSINSmove_void
  } // endif
  tmpret22 = tmp24;
  return tmpret22;
} // end-of-function


function
theExample_atscc2js_onclick()
{
//
// knd = 0
  var tmpret37
  var tmp38
  var tmplab, tmplab_js
//
  // __patsflab_theExample_atscc2js_onclick
  tmp38 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057_CBOOT_057_JS_057_TEST_057_test_libatscc2js_056_dats__theExample_atscc2js_getarg();
  tmpret37 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057_CBOOT_057_JS_057_TEST_057_test_libatscc2js_056_dats__theExample_atscc2js_arglst(tmp38);
  return tmpret37;
} // end-of-function

// dynloadflag_minit
var _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057_CBOOT_057_JS_057_TEST_057_test_libatscc2js_056_dats__dynloadflag = 0;

function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057_CBOOT_057_JS_057_TEST_057_test_libatscc2js_056_dats__dynload()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // ATSdynload()
  // ATSdynloadflag_sta(_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057_CBOOT_057_JS_057_TEST_057_test_libatscc2js_056_dats__dynloadflag(101))
  if(ATSCKiseqz(_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057_CBOOT_057_JS_057_TEST_057_test_libatscc2js_056_dats__dynloadflag)) {
    _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057_CBOOT_057_JS_057_TEST_057_test_libatscc2js_056_dats__dynloadflag = 1 ; // flag is set
  } // endif
  return/*_void*/;
} // end-of-function


function
test_libatscc2js_dynload()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057_CBOOT_057_JS_057_TEST_057_test_libatscc2js_056_dats__dynload();
  return/*_void*/;
} // end-of-function


/* ATSextcode_beg() */
//
function
the_libatscc2js_main()
{
  jQuery(document).ready(function(){test_libatscc2js_dynload();});
}
//
/* ATSextcode_end() */

/* ****** ****** */

/* end-of-compilation-unit */
