#
# A empty Makefile
#

######

PATSHOMEQ="$(PATSHOME)"

######

PATSCC=$(PATSHOMEQ)/bin/patscc
PATSOPT=$(PATSHOMEQ)/bin/patsopt

######

all::

######

all:: ; $(PATSCC) -tcats array.dats
all:: ; $(PATSCC) -tcats disjview.dats
all:: ; $(PATSCC) -tcats optview.dats
all:: ; $(PATSCC) -tcats slist.dats

######

regress:: all

######

clean::

######

cleanall::

###### end of [Makefile] ######
