#
# A simple Makefile
#
# HX-2012-10-24:
# Assuming that Pure is properly installed
#

######

.PHONY:: fact_dats.pure

######

all:: \
fact_dats.pure
fact_dats.pure: ; pure $@

###### end of [Makefile] ######
