#
# A simple Makefile
#

######

PATSCC=$(PATSHOME)/bin/patscc
PATSOPT=$(PATSHOME)/bin/patsopt
PATSLIB=$(PATSHOME)/ccomp/atslib/lib

######

RMF=rm -f

######

clean::; $(RMF) *~
clean::; $(RMF) GameOf24.h
clean::; $(RMF) GameOf24_dats.o
clean::; $(RMF) GameOf24_dats.c

cleanall:: clean

######

###### end of [Makefile] ######
