/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2017-1-30: 10h:56m
**
*/

/* ATSextcode_beg() */
//
var
theWorker_cont;
//
self.onmessage =
function(event)
{
  var k0 = theWorker_cont;
  return ats2jspre_cloref2_app(k0, 0, event.data);
}
//
function
ats2js_worker_chanpos0_recv
  (chp, k0)
{
  theWorker_cont = k0; return;
}
function
ats2js_worker_chanpos0_send
  (chp, x0, k0)
{
  postMessage(x0); return ats2jspre_cloref1_app(k0, 0);
}
//
function
ats2js_worker_chanpos1_recv
  (chp, k0)
{
  return ats2js_worker_chanpos0_recv(chp, k0);
}
function
ats2js_worker_chanpos1_send
  (chp, x0, k0)
{
  return ats2js_worker_chanpos0_send(chp, x0, k0);
}
//
/* ATSextcode_end() */

/* ATSextcode_beg() */
//
function
ats2js_worker_chanpos0_close(chp) { return self.close(); }
function
ats2js_worker_chanpos1_close(chp) { return self.close(); }
//
/* ATSextcode_end() */

function
__patsfun_1__1__1__closurerize(env0)
{
  return [function(cenv, arg0, arg1) { return __patsfun_1__1__1(cenv[1], arg0, arg1); }, env0];
}


function
__patsfun_2__2__1__closurerize(env0)
{
  return [function(cenv, arg0) { return __patsfun_2__2__1(cenv[1], arg0); }, env0];
}


function
__patsfun_39__closurerize()
{
  return [function(cenv, arg0) { return __patsfun_39(arg0); }];
}


function
list0_add_29(arg0)
{
//
// knd = 0
  var tmpret44
  var tmp45
  var tmp46
  var tmp47
  var tmplab, tmplab_js
//
  // __patsflab_list0_add_29
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab18
      if(ATSCKptriscons(arg0)) { tmplab_js = 4; break; }
      case 2: // __atstmplab19
      tmpret44 = 0;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab20
      case 4: // __atstmplab21
      tmp45 = arg0[0];
      tmp46 = arg0[1];
      tmp47 = list0_add_29(tmp46);
      tmpret44 = ats2jspre_add_int0_int0(tmp45, tmp47);
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret44;
} // end-of-function


function
ats2js_worker_rpc_server__0__1(arg0, arg1)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_rpc_server
  ats2js_worker_chanpos0_recv(arg0, __patsfun_1__1__1__closurerize(arg1));
  return/*_void*/;
} // end-of-function


function
__patsfun_1__1__1(env0, arg0, arg1)
{
//
// knd = 0
  var tmp2__1
  var tmp3__1
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_1
  tmp3__1 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chmsg_parse__32__1(arg1);
  tmp2__1 = env0[0](env0, tmp3__1);
  ats2js_worker_chanpos0_send(arg0, tmp2__1, __patsfun_2__2__1__closurerize(env0));
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chmsg_parse__32__1(arg0)
{
//
// knd = 0
  var tmpret53__1
  var tmplab, tmplab_js
//
  // __patsflab_chmsg_parse
  tmpret53__1 = aux_33__33__1(arg0);
  return tmpret53__1;
} // end-of-function


function
aux_33__33__1(arg0)
{
//
// knd = 0
  var tmpret54__1
  var tmp55__1
  var tmp56__1
  var tmp57__1
  var tmp58__1
  var tmplab, tmplab_js
//
  // __patsflab_aux_33
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab22
      if(ATSCKptriscons(arg0)) { tmplab_js = 4; break; }
      case 2: // __atstmplab23
      tmpret54__1 = null;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab24
      case 4: // __atstmplab25
      tmp55__1 = arg0[0];
      tmp56__1 = arg0[1];
      tmp57__1 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chmsg_parse__36__1(tmp55__1);
      tmp58__1 = aux_33__33__1(tmp56__1);
      tmpret54__1 = [tmp57__1, tmp58__1];
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret54__1;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chmsg_parse__36__1(arg0)
{
//
// knd = 0
  var tmpret65__1
  var tmplab, tmplab_js
//
  // __patsflab_chmsg_parse
  tmpret65__1 = parseInt(arg0);
  return tmpret65__1;
} // end-of-function


function
__patsfun_2__2__1(env0, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_2
  ats2js_worker_rpc_server__0__1(arg0, env0);
  return/*_void*/;
} // end-of-function


function
__patsfun_39(arg0)
{
//
// knd = 0
  var tmpret68
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_39
  tmpret68 = list0_add_29(arg0);
  return tmpret68;
} // end-of-function

// dynloadflag_minit
var _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_TEST_057_Worker_057_rpc_server_056_dats__dynloadflag = 0;

function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_TEST_057_Worker_057_rpc_server_056_dats__dynload()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // ATSdynload()
  // ATSdynloadflag_sta(_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_TEST_057_Worker_057_rpc_server_056_dats__dynloadflag(75))
  if(ATSCKiseqz(_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_TEST_057_Worker_057_rpc_server_056_dats__dynloadflag)) {
    _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_TEST_057_Worker_057_rpc_server_056_dats__dynloadflag = 1 ; // flag is set
    ats2js_worker_rpc_server__0__1(0, __patsfun_39__closurerize());
  } // endif
  return/*_void*/;
} // end-of-function


function
theWorker_start()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_TEST_057_Worker_057_rpc_server_056_dats__dynload();
  return/*_void*/;
} // end-of-function


/* ATSextcode_beg() */
//
theWorker_start();
//
/* ATSextcode_end() */

/* ****** ****** */

/* end-of-compilation-unit */
