/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2017-1-30: 10h:56m
**
*/

/* ATSextcode_beg() */
//
var
theWorker_cont;
//
self.onmessage =
function(event)
{
  var k0 = theWorker_cont;
  return ats2jspre_cloref2_app(k0, 0, event.data);
}
//
function
ats2js_worker_chanpos0_recv
  (chp, k0)
{
  theWorker_cont = k0; return;
}
function
ats2js_worker_chanpos0_send
  (chp, x0, k0)
{
  postMessage(x0); return ats2jspre_cloref1_app(k0, 0);
}
//
function
ats2js_worker_chanpos1_recv
  (chp, k0)
{
  return ats2js_worker_chanpos0_recv(chp, k0);
}
function
ats2js_worker_chanpos1_send
  (chp, x0, k0)
{
  return ats2js_worker_chanpos0_send(chp, x0, k0);
}
//
/* ATSextcode_end() */

/* ATSextcode_beg() */
//
function
ats2js_worker_chanpos0_close(chp) { return self.close(); }
function
ats2js_worker_chanpos1_close(chp) { return self.close(); }
//
/* ATSextcode_end() */

function
__patsfun_30__closurerize(env0, env1, env2)
{
  return [function(cenv, arg0) { return __patsfun_30(cenv[1], cenv[2], cenv[3], arg0); }, env0, env1, env2];
}


function
__patsfun_31__closurerize(env0, env1, env2)
{
  return [function(cenv, arg0) { return __patsfun_31(cenv[1], cenv[2], cenv[3], arg0); }, env0, env1, env2];
}


function
__patsfun_35__closurerize(env0, env1, env2, env3)
{
  return [function(cenv, arg0, arg1) { return __patsfun_35(cenv[1], cenv[2], cenv[3], cenv[4], arg0, arg1); }, env0, env1, env2, env3];
}


function
__patsfun_38__closurerize(env0)
{
  return [function(cenv, arg0) { return __patsfun_38(cenv[1], arg0); }, env0];
}


function
__patsfun_23__23__1__closurerize(env0, env1, env2)
{
  return [function(cenv, arg0) { return __patsfun_23__23__1(cenv[1], cenv[2], cenv[3], arg0); }, env0, env1, env2];
}


function
__patsfun_24__24__1__closurerize(env0, env1, env2)
{
  return [function(cenv, arg0) { return __patsfun_24__24__1(cenv[1], cenv[2], cenv[3], arg0); }, env0, env1, env2];
}


function
__patsfun_46__closurerize(env0, env1, env2)
{
  return [function(cenv, arg0, arg1) { return __patsfun_46(cenv[1], cenv[2], cenv[3], arg0, arg1); }, env0, env1, env2];
}


function
__patsfun_47__closurerize()
{
  return [function(cenv, arg0, arg1) { return __patsfun_47(arg0, arg1); }];
}


function
__patsfun_23__23__2__closurerize(env0, env1, env2)
{
  return [function(cenv, arg0) { return __patsfun_23__23__2(cenv[1], cenv[2], cenv[3], arg0); }, env0, env1, env2];
}


function
__patsfun_24__24__2__closurerize(env0, env1, env2)
{
  return [function(cenv, arg0) { return __patsfun_24__24__2(cenv[1], cenv[2], cenv[3], arg0); }, env0, env1, env2];
}


function
__patsfun_56__closurerize()
{
  return [function(cenv, arg0) { return __patsfun_56(arg0); }];
}


function
__patsfun_57__closurerize()
{
  return [function(cenv, arg0, arg1) { return __patsfun_57(arg0, arg1); }];
}


function
chanpos1_sstest2_29(arg0, arg1, arg2, arg3)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_chanpos1_sstest2_29
  ats2js_worker_chanpos1_send(arg0, arg2, __patsfun_30__closurerize(arg1, arg2, arg3));
  return/*_void*/;
} // end-of-function


function
__patsfun_30(env0, env1, env2, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_30
  ats2js_worker_chanpos1_send(arg0, env2, __patsfun_31__closurerize(env0, env1, env2));
  return/*_void*/;
} // end-of-function


function
__patsfun_31(env0, env1, env2, arg0)
{
//
// knd = 0
  var tmp47
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_31
  tmp47 = ats2jspre_ref(3);
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chanpos1_repeat_disj__21__1(tmp47, arg0, env0, __patsfun_46__closurerize(env1, env2, tmp47));
  return/*_void*/;
} // end-of-function


function
check_32(env0, env1, env2, arg0)
{
//
// knd = 0
  var tmpret48
  var tmp49
  var tmp50
  var tmp51
  var tmp53
  var tmplab, tmplab_js
//
  // __patsflab_check_32
  tmp49 = ats2jspre_ref_get_elt(env2);
  tmp51 = ats2jspre_mul_int0_int0(env0, env1);
  tmp50 = ats2jspre_eq_int0_int0(arg0, tmp51);
  if(tmp50) {
    ats2jspre_ref_set_elt(env2, 0);
  } else {
    tmp53 = ats2jspre_sub_int0_int0(tmp49, 1);
    ats2jspre_ref_set_elt(env2, tmp53);
  } // endif
  tmpret48 = tmp50;
  return tmpret48;
} // end-of-function


function
fserv_34(env0, env1, env2, arg0, arg1)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_fserv_34
  ats2js_worker_chanpos1_recv(arg0, __patsfun_35__closurerize(env0, env1, env2, arg1));
  return/*_void*/;
} // end-of-function


function
__patsfun_35(env0, env1, env2, env3, arg0, arg1)
{
//
// knd = 0
  var tmp59
  var tmp60
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_35
  tmp60 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chmsg_parse__36__1(arg1);
  tmp59 = check_32(env0, env1, env2, tmp60);
  ats2js_worker_chanpos1_send(arg0, tmp59, __patsfun_38__closurerize(env3));
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chmsg_parse__36__1(arg0)
{
//
// knd = 0
  var tmpret61__1
  var tmplab, tmplab_js
//
  // __patsflab_chmsg_parse
  tmpret61__1 = parseInt(arg0);
  return tmpret61__1;
} // end-of-function


function
__patsfun_38(env0, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_38
  env0[0](env0, arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chanpos1_repeat_disj__21__1(env0, arg0, arg1, arg2)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_chanpos1_repeat_disj
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chanpos1_repeat_disj__init__26__1();
  loop_22__22__1(env0, arg0, arg1, arg2);
  return/*_void*/;
} // end-of-function


function
loop_22__22__1(env0, arg0, arg1, arg2)
{
//
// knd = 0
  var tmp35__1
  var tmplab, tmplab_js
//
  // __patsflab_loop_22
  tmp35__1 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chanpos1_repeat_disj__choose__33__1(env0);
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chanpos1_repeat_disj__fwork_tag__28__1(tmp35__1);
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab15
      if(!ATSCKpat_int(tmp35__1, 0)) { tmplab_js = 3; break; }
      case 2: // __atstmplab16
      ats2js_worker_chanpos0_send(arg0, tmp35__1, arg1);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab17
      ats2js_worker_chanpos0_send(arg0, tmp35__1, __patsfun_23__23__1__closurerize(arg1, arg2, env0));
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chanpos1_repeat_disj__choose__33__1(env0)
{
//
// knd = 0
  var tmpret54__1
  var tmp55__1
  var tmp56__1
  var tmplab, tmplab_js
//
  // __patsflab_chanpos1_repeat_disj__choose
  tmp56__1 = ats2jspre_ref_get_elt(env0);
  tmp55__1 = ats2jspre_gt_int0_int0(tmp56__1, 0);
  if(tmp55__1) {
    tmpret54__1 = 1;
  } else {
    tmpret54__1 = 0;
  } // endif
  return tmpret54__1;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chanpos1_repeat_disj__fwork_tag__28__1(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_chanpos1_repeat_disj__fwork_tag
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
__patsfun_23__23__1(env0, env1, env2, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_23
  env1[0](env1, arg0, __patsfun_24__24__1__closurerize(env0, env1, env2));
  return/*_void*/;
} // end-of-function


function
__patsfun_24__24__1(env0, env1, env2, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_24
  loop_22__22__1(env2, arg0, env0, env1);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chanpos1_repeat_disj__init__26__1()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_chanpos1_repeat_disj__init
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
__patsfun_46(env0, env1, env2, arg0, arg1)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_46
  fserv_34(env0, env1, env2, arg0, arg1);
  return/*_void*/;
} // end-of-function


function
__patsfun_47(arg0, arg1)
{
//
// knd = 0
  var tmp79
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_47
  tmp79 = ats2jspre_ref(3);
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chanpos1_repeat_disj__21__2(tmp79, arg0, __patsfun_56__closurerize(), __patsfun_57__closurerize());
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chanpos1_repeat_disj__21__2(env0, arg0, arg1, arg2)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_chanpos1_repeat_disj
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chanpos1_repeat_disj__init__26__2();
  loop_22__22__2(env0, arg0, arg1, arg2);
  return/*_void*/;
} // end-of-function


function
loop_22__22__2(env0, arg0, arg1, arg2)
{
//
// knd = 0
  var tmp35__2
  var tmplab, tmplab_js
//
  // __patsflab_loop_22
  tmp35__2 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chanpos1_repeat_disj__choose__48__1(env0);
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chanpos1_repeat_disj__fwork_tag__28__2(tmp35__2);
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab15
      if(!ATSCKpat_int(tmp35__2, 0)) { tmplab_js = 3; break; }
      case 2: // __atstmplab16
      ats2js_worker_chanpos0_send(arg0, tmp35__2, arg1);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab17
      ats2js_worker_chanpos0_send(arg0, tmp35__2, __patsfun_23__23__2__closurerize(arg1, arg2, env0));
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chanpos1_repeat_disj__choose__48__1(env0)
{
//
// knd = 0
  var tmpret80__1
  var tmp81__1
  var tmp83__1
  var tmp84__1
  var tmplab, tmplab_js
//
  // __patsflab_chanpos1_repeat_disj__choose
  tmp81__1 = ats2jspre_ref_get_elt(env0);
  tmp83__1 = ats2jspre_sub_int0_int0(tmp81__1, 1);
  ats2jspre_ref_set_elt(env0, tmp83__1);
  tmp84__1 = ats2jspre_gt_int0_int0(tmp81__1, 0);
  if(tmp84__1) {
    tmpret80__1 = 1;
  } else {
    tmpret80__1 = 0;
  } // endif
  return tmpret80__1;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chanpos1_repeat_disj__fwork_tag__28__2(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_chanpos1_repeat_disj__fwork_tag
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
__patsfun_23__23__2(env0, env1, env2, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_23
  env1[0](env1, arg0, __patsfun_24__24__2__closurerize(env0, env1, env2));
  return/*_void*/;
} // end-of-function


function
__patsfun_24__24__2(env0, env1, env2, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_24
  loop_22__22__2(env2, arg0, env0, env1);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chanpos1_repeat_disj__init__26__2()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_chanpos1_repeat_disj__init
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
__patsfun_56(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_56
  ats2js_worker_chanpos1_close(arg0);
  return/*_void*/;
} // end-of-function


function
__patsfun_57(arg0, arg1)
{
//
// knd = 0
  var tmp101
  var tmp102
  var tmp103
  var tmp104
  var tmp105
  var tmp106
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_57
  tmp103 = ats2jspre_JSmath_random();
  tmp102 = ats2jspre_mul_int_double(100, tmp103);
  tmp101 = ats2jspre_double2int(tmp102);
  tmp106 = ats2jspre_JSmath_random();
  tmp105 = ats2jspre_mul_int_double(100, tmp106);
  tmp104 = ats2jspre_double2int(tmp105);
  chanpos1_sstest2_29(arg0, arg1, tmp101, tmp104);
  return/*_void*/;
} // end-of-function

// dynloadflag_minit
var _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_TEST_057_Worker_057_test3_server_056_dats__dynloadflag = 0;

function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_TEST_057_Worker_057_test3_server_056_dats__dynload()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // ATSdynload()
  // ATSdynloadflag_sta(_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_TEST_057_Worker_057_test3_server_056_dats__dynloadflag(154))
  if(ATSCKiseqz(_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_TEST_057_Worker_057_test3_server_056_dats__dynloadflag)) {
    _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_TEST_057_Worker_057_test3_server_056_dats__dynloadflag = 1 ; // flag is set
    ats2js_worker_chanpos1_recv(0, __patsfun_47__closurerize());
  } // endif
  return/*_void*/;
} // end-of-function


function
theWorker_start()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_TEST_057_Worker_057_test3_server_056_dats__dynload();
  return/*_void*/;
} // end-of-function


/* ATSextcode_beg() */
//
theWorker_start();
//
/* ATSextcode_end() */

/* ****** ****** */

/* end-of-compilation-unit */
