/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2017-1-30: 10h:56m
**
*/

/* ATSextcode_beg() */
//
function
ats2js_worker_channeg0_new_file
  (file) { var chn = new Worker(file); return chn; }
//
/* ATSextcode_end() */

/* ATSextcode_beg() */
//
function
ats2js_worker_channeg0_close(chn) { return chn.terminate(); }
function
ats2js_worker_channeg1_close(chn) { return chn.terminate(); }
//
/* ATSextcode_end() */

/* ATSextcode_beg() */
//
function
ats2js_worker_channeg0_send(chn, k0)
{
  chn.onmessage =
  function(event)
    { return ats2jspre_cloref2_app(k0, chn, event.data); };
  return/*void*/;
}
function
ats2js_worker_channeg0_recv(chn, x0, k0)
{
  chn.postMessage(x0); return ats2jspre_cloref1_app(k0, chn);
}
//
function
ats2js_worker_channeg1_send
  (chn, k0)
{
  return ats2js_worker_channeg0_send(chn, k0);
}
function
ats2js_worker_channeg1_recv
  (chn, x0, k0)
{
  return ats2js_worker_channeg0_recv(chn, x0, k0);
}
//
/* ATSextcode_end() */

/* ATSextcode_beg() */
//
function
console_log(x) { return console.log(x); }
//
function
theArg1_set(a1)
{
  document.getElementById('theArg1').value = a1;
}
function
theArg2_set(a2)
{
  document.getElementById('theArg2').value = a2;
}
function
theResult_get()
{
  return parseInt(document.getElementById('theResult').value);
}
function
theResult_set(value)
{
  document.getElementById('theResult').value = value;
}
//
/* ATSextcode_end() */

/* ATSextcode_beg() */
//
var
Started = false;
//
function
Start_onclick()
{
  if (!Started)
  {
    Started = true; return StartIt();
  } else
  {
    alert ('The session is in progress!'); return;
  }
}
//
var
AnswerIt = 0;
var
AnswerIt_do = 0;
//
function
AnswerIt_onclick()
{
  if (AnswerIt)
  {
    AnswerIt = 0;
    return ats2jspre_cloref0_app(AnswerIt_do);
  } else {
    alert('The AnswerIt button is not ready yet!'); return;
  } // end of [if]
}
//
function
AnswerIt_do_set(fclo)
  { AnswerIt = 1; AnswerIt_do = fclo; return; }
//
/* ATSextcode_end() */

function
__patsfun_31__closurerize()
{
  return [function(cenv, arg0) { return __patsfun_31(arg0); }];
}


function
__patsfun_33__closurerize()
{
  return [function(cenv, arg0) { return __patsfun_33(arg0); }];
}


function
__patsfun_24__24__1__closurerize(env0, env1)
{
  return [function(cenv, arg0, arg1) { return __patsfun_24__24__1(cenv[1], cenv[2], arg0, arg1); }, env0, env1];
}


function
__patsfun_25__25__1__closurerize(env0, env1)
{
  return [function(cenv, arg0) { return __patsfun_25__25__1(cenv[1], cenv[2], arg0); }, env0, env1];
}


function
__patsfun_43__closurerize()
{
  return [function(cenv, arg0, arg1) { return __patsfun_43(arg0, arg1); }];
}


function
__patsfun_44__closurerize(env0)
{
  return [function(cenv, arg0, arg1) { return __patsfun_44(cenv[1], arg0, arg1); }, env0];
}


function
__patsfun_45__closurerize(env0, env1)
{
  return [function(cenv, arg0, arg1) { return __patsfun_45(cenv[1], cenv[2], arg0, arg1); }, env0, env1];
}


function
__patsfun_49__closurerize(env0, env1)
{
  return [function(cenv) { return __patsfun_49(cenv[1], cenv[2]); }, env0, env1];
}


function
__patsfun_50__closurerize(env0)
{
  return [function(cenv, arg0) { return __patsfun_50(cenv[1], arg0); }, env0];
}


function
__patsfun_51__closurerize(env0)
{
  return [function(cenv, arg0, arg1) { return __patsfun_51(cenv[1], arg0, arg1); }, env0];
}


function
StartIt()
{
//
// knd = 0
  var tmp46
  var tmplab, tmplab_js
//
  // __patsflab_StartIt
  tmp46 = ats2js_worker_channeg0_new_file("./test2_server_dats_.js");
  ats2js_worker_channeg1_recv(tmp46, 0, __patsfun_31__closurerize());
  return/*_void*/;
} // end-of-function


function
__patsfun_31(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_31
  StartIt_aft(arg0);
  return/*_void*/;
} // end-of-function


function
StartIt_aft(arg0)
{
//
// knd = 0
  var tmp50
  var tmplab, tmplab_js
//
  // __patsflab_StartIt_aft
  tmp50 = __patsfun_33__closurerize();
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__channeg1_repeat_disj__22__1(arg0, tmp50, __patsfun_43__closurerize());
  return/*_void*/;
} // end-of-function


function
__patsfun_33(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_33
  Started = false;
  ats2js_worker_channeg1_close(arg0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__channeg1_repeat_disj__22__1(arg0, arg1, arg2)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_channeg1_repeat_disj
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__channeg1_repeat_disj__init__27__1();
  loop_23__23__1(arg0, arg1, arg2);
  return/*_void*/;
} // end-of-function


function
loop_23__23__1(arg0, arg1, arg2)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_loop_23
  ats2js_worker_channeg0_send(arg0, __patsfun_24__24__1__closurerize(arg1, arg2));
  return/*_void*/;
} // end-of-function


function
__patsfun_24__24__1(env0, env1, arg0, arg1)
{
//
// knd = 0
  var tmp37__1
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_24
  tmp37__1 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chmsg_parse__38__1(arg1);
  _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__channeg1_repeat_disj__fwork_tag__34__1(tmp37__1);
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab15
      if(!ATSCKpat_int(tmp37__1, 0)) { tmplab_js = 3; break; }
      case 2: // __atstmplab16
      env0[0](env0, arg0);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab17
      env1[0](env1, arg0, __patsfun_25__25__1__closurerize(env0, env1));
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chmsg_parse__38__1(arg0)
{
//
// knd = 0
  var tmpret60__1
  var tmplab, tmplab_js
//
  // __patsflab_chmsg_parse
  tmpret60__1 = parseInt(arg0);
  return tmpret60__1;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__channeg1_repeat_disj__fwork_tag__34__1(arg0)
{
//
// knd = 0
  var tmp52__1
  var tmp53__1
  var tmplab, tmplab_js
//
  // __patsflab_channeg1_repeat_disj__fwork_tag
  tmp53__1 = ats2jspre_String(arg0);
  tmp52__1 = ats2jspre_string_append("fwork_tag: tag = ", tmp53__1);
  console_log(tmp52__1);
  return/*_void*/;
} // end-of-function


function
__patsfun_25__25__1(env0, env1, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_25
  loop_23__23__1(arg0, env0, env1);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__channeg1_repeat_disj__init__27__1()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_channeg1_repeat_disj__init
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
__patsfun_43(arg0, arg1)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_43
  ats2js_worker_channeg1_send(arg0, __patsfun_44__closurerize(arg1));
  return/*_void*/;
} // end-of-function


function
__patsfun_44(env0, arg0, arg1)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_44
  ats2js_worker_channeg1_send(arg0, __patsfun_45__closurerize(env0, arg1));
  return/*_void*/;
} // end-of-function


function
__patsfun_45(env0, env1, arg0, arg1)
{
//
// knd = 0
  var tmp70
  var tmp72
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_45
  tmp70 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chmsg_parse__38__2(env1);
  tmp72 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chmsg_parse__38__3(arg1);
  ReplyIt(arg0, env0, tmp70, tmp72);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chmsg_parse__38__2(arg0)
{
//
// knd = 0
  var tmpret60__2
  var tmplab, tmplab_js
//
  // __patsflab_chmsg_parse
  tmpret60__2 = parseInt(arg0);
  return tmpret60__2;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chmsg_parse__38__3(arg0)
{
//
// knd = 0
  var tmpret60__3
  var tmplab, tmplab_js
//
  // __patsflab_chmsg_parse
  tmpret60__3 = parseInt(arg0);
  return tmpret60__3;
} // end-of-function


function
ReplyIt(arg0, arg1, arg2, arg3)
{
//
// knd = 0
  var tmp85
  var tmplab, tmplab_js
//
  // __patsflab_ReplyIt
  theArg1_set(arg2);
  theArg2_set(arg3);
  theResult_set("");
  tmp85 = __patsfun_49__closurerize(arg0, arg1);
  AnswerIt_do_set(tmp85);
  return/*_void*/;
} // end-of-function


function
__patsfun_49(env0, env1)
{
//
// knd = 0
  var tmp79
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_49
  tmp79 = theResult_get();
  ats2js_worker_channeg1_recv(env0, tmp79, __patsfun_50__closurerize(env1));
  return/*_void*/;
} // end-of-function


function
__patsfun_50(env0, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_50
  ats2js_worker_channeg1_send(arg0, __patsfun_51__closurerize(env0));
  return/*_void*/;
} // end-of-function


function
__patsfun_51(env0, arg0, arg1)
{
//
// knd = 0
  var tmp82
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_51
  tmp82 = _057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chmsg_parse__52__1(arg1);
  PostRep(arg0, env0, tmp82);
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2js_057_SATS_057_Worker_057_channel_056_sats__chmsg_parse__52__1(arg0)
{
//
// knd = 0
  var tmpret83__1
  var tmplab, tmplab_js
//
  // __patsflab_chmsg_parse
  tmpret83__1 = arg0;
  return tmpret83__1;
} // end-of-function


function
PostRep(arg0, arg1, arg2)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_PostRep
  arg1[0](arg1, arg0);
  if(arg2) {
    ats2jspre_alert("The replied answer is right :)");
  } else {
    ats2jspre_alert("The replied answer is wrong :(");
  } // endif
  return/*_void*/;
} // end-of-function


/* ****** ****** */

/* end-of-compilation-unit */
