<?php
/*
**
** The PHP code is generated by atscc2php
** The starting compilation time is: 2016-10-8: 10h:20m
**
*/

// ATSassume(_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_contrib_057_libatscc_057_libatscc2php_057_basics_php_056_sats__array0_vt0ype_type)

function
ats2phppre_ML_array0_make_elt($arg0, $arg1)
{
//
  $tmpret0 = NULL;
//
  __patsflab_array0_make_elt:
  $tmpret0 = ats2phppre_arrszref_make_elt($arg0, $arg1);
  return $tmpret0;
} // end-of-function


function
ats2phppre_ML_array0_size($arg0)
{
//
  $tmpret1 = NULL;
//
  __patsflab_array0_size:
  $tmpret1 = ats2phppre_arrszref_size($arg0);
  return $tmpret1;
} // end-of-function


function
ats2phppre_ML_array0_get_at($arg0, $arg1)
{
//
  $tmpret2 = NULL;
//
  __patsflab_array0_get_at:
  $tmpret2 = ats2phppre_arrszref_get_at($arg0, $arg1);
  return $tmpret2;
} // end-of-function


function
ats2phppre_ML_array0_set_at($arg0, $arg1, $arg2)
{
//
//
  __patsflab_array0_set_at:
  ats2phppre_arrszref_set_at($arg0, $arg1, $arg2);
  return/*_void*/;
} // end-of-function


function
ats2phppre_ML_array0_exch_at($arg0, $arg1, $arg2)
{
//
  $tmpret4 = NULL;
//
  __patsflab_array0_exch_at:
  $tmpret4 = ats2phppre_arrszref_exch_at($arg0, $arg1, $arg2);
  return $tmpret4;
} // end-of-function

/* ****** ****** */

/* end-of-compilation-unit */
?>
