<?php
/*
**
** The PHP code is generated by atscc2php
** The starting compilation time is: 2014-9-19: 22h:35m
**
*/

function
atslangweb__patsopt_tcats_code_0_($arg0)
{
/*
  // $tmpret1
*/
  __patsflab_patsopt_tcats_code_0_:
  $tmpret1 = atslangweb__patsopt_tcats_code__2__1($arg0);
  return $tmpret1;
} // end-of-function


function
atslangweb__patsopt_tcats_code__2__1($arg0)
{
/*
  // $tmpret2__1
  // $tmp3__1
  // $tmp4__1
  // $tmp5__1
*/
  __patsflab_patsopt_tcats_code:
  $tmp3__1 = atslangweb__tmpfile_make_string("patsopt_tcats_", $arg0);
  $tmp4__1 = atslangweb__patsopt_tcats_file__4__1($tmp3__1);
  $tmp5__1 = atslangweb__tmpfile_unlink($tmp3__1);
  $tmpret2__1 = $tmp4__1;
  return $tmpret2__1;
} // end-of-function


function
atslangweb__patsopt_tcats_file__4__1($arg0)
{
/*
  // $tmpret10__1
  // $tmp11__1
  // $tmp12__1
  // $tmp13__1
  // $tmp14__1
  // $tmp15__1
  // $tmp16__1
  // $tmp17__1
*/
  __patsflab_patsopt_tcats_file:
  $tmp11__1 = atslangweb__tmpfile_make_nil("patsopt_tcats_");
  $tmp12__1 = atslangweb__patsopt_tcats_command__6__1($arg0, $tmp11__1);
  $tmp13__1 = atslangweb__exec_retval($tmp12__1);
  $tmp15__1 = ats2phppre_eq_int0_int0($tmp13__1, 0);
  if($tmp15__1) {
    $tmp14__1 = array(0, "Typechecking passed!");
  } else {
    $tmp16__1 = atslangweb__tmpfile2string($tmp11__1);
    $tmp14__1 = array(1, $tmp16__1);
  } // endif
  $tmp17__1 = atslangweb__tmpfile_unlink($tmp11__1);
  $tmpret10__1 = $tmp14__1;
  return $tmpret10__1;
} // end-of-function


function
atslangweb__patsopt_tcats_command__6__1($arg0, $arg1)
{
/*
  // $tmpret26__1
  // $tmp27__1
*/
  __patsflab_patsopt_tcats_command:
  $tmp27__1 = atslangweb__patsopt_command__0__1();
  $tmpret26__1 = sprintf("%s 2>%s --typecheck -d %s", $tmp27__1, $arg1, $arg0);
  return $tmpret26__1;
} // end-of-function


function
atslangweb__patsopt_command__0__1()
{
/*
  // $tmpret0__1
*/
  __patsflab_patsopt_command:
  $tmpret0__1 = "patsopt";
  return $tmpret0__1;
} // end-of-function


function
atslangweb__patsopt_tcats_code_1_($arg0)
{
/*
  // $tmpret31
  // $tmp32
*/
  __patsflab_patsopt_tcats_code_1_:
  $tmp32 = sprintf("%s\n%s\n%s\n", $GLOBALS['atslangweb__patsopt_code_preamble'], $arg0, $GLOBALS['atslangweb__patsopt_code_postamble']);
  $tmpret31 = atslangweb__patsopt_tcats_code_0_($tmp32);
  return $tmpret31;
} // end-of-function

/* ****** ****** */

/* end-of-compilation-unit */
?>
