/*
**
** The C code is generated by [ATS/Postiats-0-3-0]
** The starting compilation time is: 2016-12-27: 17h:19m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/home/hwxi/Research/ATS-Postiats/libats/SATS/dynarray.sats: 1467(line=40, offs=1) -- 1510(line=42, offs=3)
*/

#include "libats/CATS/dynarray.cats"
/*
/home/hwxi/Research/ATS-Postiats/libats/SATS/stringbuf.sats: 1534(line=41, offs=1) -- 1578(line=43, offs=3)
*/

#include "libats/CATS/stringbuf.cats"
/*
/home/hwxi/Research/ATS-Postiats-contrib/contrib/libats-/hwxi/cstream/SATS/cstream.sats: 1712(line=43, offs=1) -- 1749(line=44, offs=30)
*/
/*
/home/hwxi/Research/ATS-Postiats/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/home/hwxi/Research/ATS-Postiats/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/home/hwxi/Research/ATS-Postiats/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/home/hwxi/Research/ATS-Postiats-contrib/contrib/libats-/hwxi/cstream/SATS/cstream.sats: 3486(line=135, offs=1) -- 3528(line=136, offs=35)
*/
/*
/home/hwxi/Research/ATS-Postiats/libats/SATS/stringbuf.sats: 1534(line=41, offs=1) -- 1578(line=43, offs=3)
*/

#include "libats/CATS/stringbuf.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
/home/hwxi/Research/ATS-Postiats-contrib/projects/MEDIUM/CATS-atsccomp/CATS-atscc2js/.CATS-parsemit/catsparse.sats: 1764(line=82, offs=1) -- 1787(line=82, offs=24)
*/
ATSdynexn_dec(CATSPARSE__FatalErrorExn) ;
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057__056_CATS_055_parsemit_057_catsparse_056_sats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057__056_CATS_055_parsemit_057_catsparse_056_sats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057__056_CATS_055_parsemit_057_catsparse_056_sats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057__056_CATS_055_parsemit_057_catsparse_056_sats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_hwxi_057_Research_057_ATS_055_Postiats_055_contrib_057_projects_057_MEDIUM_057_CATS_055_atsccomp_057_CATS_055_atscc2js_057__056_CATS_055_parsemit_057_catsparse_056_sats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */
#endif // end of [#if(0)]

/* ****** ****** */

/* end-of-compilation-unit */
