#
#
# A Simple Makefile
#
#

######

MAKE=make

######

cleanall::
cleanall:: ; $(MAKE) -C CHAP_START cleanall
cleanall:: ; $(MAKE) -C CHAP_PROGELEM cleanall
cleanall:: ; $(MAKE) -C CHAP_FUNCTION cleanall
cleanall:: ; $(MAKE) -C CHAP_DATATYPE cleanall
cleanall:: ; $(MAKE) -C CHAP_POLYMORPH cleanall
cleanall:: ; $(MAKE) -C CHAP_EFFECTFUL cleanall
cleanall:: ; $(MAKE) -C CHAP_MODULARITY cleanall
cleanall:: ; $(MAKE) -C CHAP_CINTERACT cleanall
cleanall:: ; $(MAKE) -C CHAP_DEPTYPES cleanall
cleanall:: ; $(MAKE) -C CHAP_DEPDTREF cleanall
cleanall:: ; $(MAKE) -C CHAP_THMPRVING cleanall
cleanall:: ; $(MAKE) -C CHAP_PRGTHMPRV cleanall
cleanall:: ; $(MAKE) -C CHAP_VVTINTRO cleanall
cleanall:: ; $(MAKE) -C CHAP_DATAVIEW cleanall
cleanall:: ; $(MAKE) -C CHAP_DATAVTYPE cleanall
cleanall:: ; $(MAKE) -C CHAP_ABSVTYPE cleanall

###### end of [Makefile] ######