#
# A simple Makefile
#
######

include \
$(PATSHOME)/share/atsmake-pre.mk

######

SOURCES_SATS += atslex.sats

######

SOURCES_DATS += atslex_main.dats
SOURCES_DATS += atslex_charset.dats

######

MYTARGET=atslex

######

include $(PATSHOME)/share/atsmake-post.mk

###### end of [Makefile] ######